### ISSUE TITLE
How to indent complex indented expressions inside of lists and other partially-indented contexts

### ISSUE THREAD

**Issue by avh4** [avh4/elm-format#10]
For example,

```elm
multilineExpressionsInsideList =
    [ let
        x = 1
      in
        x
    , if True then
        2
      else if False then
        3
      else
        4
    , case True of
        _ ->
            5
    , [ 6
      , 7
      ]
        |> head
        |> Maybe.withDefault 8
    , \a ->
        9
    ]
```

The above formatting seems the most natural from the currently defined rules, but this is strange because the `else` is indented two spaces to line up with the `if`, and the body of the `if` is indented 4 spaces from the previous line, but the body of the `else` is indented 2 spaces.

The most obvious alternative is to shift the bodies another two spaces over, but this is strange because it breaks us out of the 4-space indentation grid.

This will also apply to `let`, `case`, lambdas, and probably any other expression whose second line can be indented.  This also applies to multiline tuples and records.  This probably also applies to tuple and record type definitions.

A real-world example:

```elm
        div
            [ classList classes ]
            [ div
                [ class "modal-backdrop" ]
                []
            , div
                [ class "school-search-modal" ]
                [ div
                    [ class "school-search-modal-header" ]
                    [ viewHeader address model ]
                , div
                    [ class "school-search-modal-body" ]
                    [ viewBody address model ]
                ]
            ]
```

**Comment by Apanatshka** [comment]
I'm confused. The record example seems to use 4-space indent consistently, but the list example doesn't...

**Comment by avh4** [comment]
I guess that's true, let's focus on the list example for this thread.  I'll remove the record one from the description.

**Comment by rtfeldman** [comment]
Here is a real-world example:

```elm
        div
            [ classList classes ]
            [ div
                [ class "modal-backdrop" ]
                []
            , div
                [ class "school-search-modal" ]
                [ div
                    [ class "school-search-modal-header" ]
                    [ viewHeader address model ]
                , div
                    [ class "school-search-modal-body" ]
                    [ viewBody address model ]
                ]
            ]
```

We basically did what you did above: deviate from the 4-space grid as little as possible.

In my experience, this is the most common case for multiline expressions inside list literals: a function being applied, followed by indented arguments. I agree that it's a bit weird that things like `else` will be de facto indented 2 spaces instead of 4, but I don't think it will come up often enough in practice to be a cause for concern.

**Comment by Apanatshka** [comment]
I think I understand the issue now, and have formed an opinion (which also relates to what I think about #18):

The 4-space<sup>1</sup> grid is not holy. Easily recognisable code patterns are much more important. So if you normally have a definition in a `let` indented by four spaces:

```elm
f a b =
    let
        x = 0
    in
        x + a * b
```

Then you should have a four space difference between the starting column of the `let` and of the definition in other contexts too:

```elm
f2 a b =
    [ let
          x = 0
      in
          x + a * b
    , Just Nothing
    ]
```

So for the larger example this looks like:

```elm
multilineExpressionsInsideList =
    [ let
          x = 1
      in
          x
    , if True then
          2
      else if False then
          3
      else
          4
    , case True of
          _ ->
              5
    , [ 6
      , 7
      ]
      |> head
      |> Maybe.withDefault 8
    , \a ->
          9
    ]
```

<sup>1</sup> I don't remember talking about what size the indentation should be and don't see it in the Google doc. Did we agree on 4 spaces? Because I *much* prefer 2 spaces actually.

**Comment by rtfeldman** [comment]
I tried both based on Laszlo's style guide suggestion of 4, and I have a minor aesthetic preference for 4.

I can get behind the idea of 2 making things more consistent and fixing edge cases though. Maybe we should try 2 and see how it goes? Quick enough change I'd assume.

**Comment by avh4** [comment]
Discussion of 2 vs 4 space indent can be moved to another issue.  (I thought Evan had a strong preference for 4 spaces?)

Assuming we keep 4 spaces, there seems to be agreement on this issue.

However, there is an edge case with nested lists.  Does this look good:

```elm
foo =
    [ [ 1 ]
    , [ 20
      , 21
      ]
    , [ [ 30
        , 31
        ]
            |> head
            |> Maybe.withDefault 0
      ]
    ]

**Comment by avh4** [comment]
Here is another bad edge-case:

```elm
(==/==) a b = a

multilineParenthesizedExpressions =
    graphHeight
        / ( if range == 0 then
            0.1
          else
            toFloat range
        )
        ==/== ( if range == 0 then
            0.1
          else
            toFloat range
        )
```

The `if` and `else` are not aligned.

**Comment by rtfeldman** [comment]
How about putting the `if` and the parens on their own lines? I did a lot of that stuff in my trailing-commas days (including with lists and braces), and it's very easy to read:

```elm
(==/==) a b = a

multilineParenthesizedExpressions =
    graphHeight
        /
        (
            if range == 0 then
                0.1
            else
                toFloat range
        )
        ==/==
        (
            if range == 0 then
                0.1
            else
                toFloat range
        )
```

**Comment by avh4** [comment]
So I wrote a test case and ran it through the formatter, and it currently formats like this, which I think akes enough sense for now, given that it took no effort to implement:

```elm
multilineParenthesizedExpressions =
    graphHeight
        / ( if range == 0 then
              0.1
            else
              toFloat range
          )
        ==/== ( if range == 0 then
                  0.2
                else
                  toFloat (range - 1)
              )
        <<>> ( if range == 0 then
                 -1.0
               else
                 0.0
             )
```

We can consider revisiting at a later time after seeing more real-world examples.
