### ISSUE TITLE
elm-format removes comments without a trace

### ISSUE THREAD

**Issue by kika** [avh4/elm-format#102]
```elm
type alias ChangesState =
    { 
        -- It's Int in CouchDB and String in Cloudant
        -- using String as a least common denominator
        last_seen : String
    }
```

gets "formatted" to just
```elm
type alias ChangesState =
    { last_seen : String
    }
```

Not really friendly :-)

Bug or expected behaviour?

**Comment by kika** [comment]
The same happens to block comment ```{- blah-blah-blah -}``` at the same place

**Comment by avh4** [comment]
Thanks, there is still a long list of places comments need to be handled (https://github.com/avh4/elm-format/issues/3)  This should be fixed when that is done.

**Comment by avh4** [comment]
Handling of comments in record types is added in 9d0c2f4.
