### ISSUE TITLE
handling modules with lots of exports

### ISSUE THREAD

**Issue by Bogdanp** [avh4/elm-format#106]
If I run elm-format (built from 9584c6d8223098ef911abd43cecd6b9171993e9b) on elm-combine's [Combine.elm](https://github.com/Bogdanp/elm-combine/blob/master/src/Combine.elm) it ends up turning

``` Elm
module Combine ( Parser, Context, primitive
               , parse, app, rec
               , bimap, map, mapError
               , andThen, andMap
               , fail, succeed, string, regex, while, end
               , or, choice, optional, maybe, many, many1, manyTill
               , sepBy, sepBy1, skip, skipMany, skipMany1
               , chainl, chainr, count, between, parens
               , braces, brackets
               ) where
```

into

``` Elm
module Combine (Parser, Context, primitive, parse, app, rec, bimap, map, mapError, andThen, andMap, fail, succeed, string, regex, while, end, or, choice, optional, maybe, many, many1, manyTill, sepBy, sepBy1, skip, skipMany, skipMany1, chainl, chainr, count, between, parens, braces, brackets) where
```

Obviously, this is not ideal. I think grouping exports like I have done above is common practice ([here's](https://github.com/elm-lang/core/blob/master/src/Basics.elm) an example from core) so maybe elm-format should leave exports as they are.

**Comment by jeremy-w** [comment]
I came here to mention the same thing. I was aghast to find all my exports collapsed into a mega-line of doom by elm-format. Lucky thing it's very clear about mutating the file, and I'm using git, so no harm done. :)

There's often meaning to the grouping of exports into lines. I've even seen the export groupings mirror the sections in the module docs before, which makes that significance explicit.

If the doc<->export grouping correspondence is actually standard, we might be able to recreate the export groupings from docs, and pick up functions missing from the module docs and vice-versa doc'd functions missing from the module exports. Could be a nifty cross-check.

**Comment by mgold** [comment]
I like the idea of the nifty cross-check but let's start with the dumber solution of leaving multiline exports alone.
