### ISSUE TITLE
Version numbering strategy (should we try to track Elm's version number?)

### ISSUE THREAD

**Issue by avh4** [avh4/elm-format#112]
Should the first official release be 1.0, or should we mirror the Elm version numbers?  (Meaning the first official release would be 0.16, to match Elm 0.16.)

What are the pros and cons of each approach?

**Comment by Janiczek** [comment]
Being so closely tied to Elm compiler, I would mirror the Elm version numbers.
I just don't know about subsequent updates - would that be `0.16.1` etc.?

Pros:
- You know right off the bat that something's wrong if the numbers don't match.

Cons:
- No semver?

**Comment by rtfeldman** [comment]
I think it's safe to assume it will end up packaged with the Elm platform at some point, so probably no big deal if it does its own thing before then. :smile:

**Comment by deadfoxygrandpa** [comment]
We went through this with the Sublime Text plugin, too, and eventually decided to mirror the Elm version numbers, but only the major version numbers. So `Elm Language Support 0.16.x` is specifically designed to support Elm v 0.16. If I release new versions in between Elm releases, I just bump the smallest version number. It's not semvar but it's so tightly coupled to Elm itself that I don't think it really matters.

**Comment by avh4** [comment]
I think I'd like to do:

`<elm-major>.<elm-minor>.<major>.<minor>.<patch>`

in order to track the elm version *and* keep some semblance of semver for elm-format itself.  So the first official release would be `elm-format-0.17.1.0.0`

**Comment by mgold** [comment]
What about `elm-format-0.17-1.0.0`, with a dash? It helps break it up a bit.

**Comment by avh4** [comment]
Unfortunately, haskell (or at least cabal) doesn't allow dots after a dash in the version number.

**Comment by avh4** [comment]
Hmm... maybe the package name could be "elm-format-0.17", and the version number could be "1.0.0"...

**Comment by mgold** [comment]
Do you mean dashes after dots? In which case, I like your original idea.

**Comment by avh4** [comment]
Cabal will let you have dashes after dots, but not dots after dashes.

valid versions:
  - `1.0.0-alpha`
  - `1.0.0-2000-alpha-017`

invalid versions:
  - `1.0.0-alpha-1.0`
  - `1-0.17`

**Comment by avh4** [comment]
elm-format has been supporting multiple Elm versions for a while now, so having the elm-format version independent from the Elm version seems to be working fine.
