### ISSUE TITLE
Floats converting to scientific notation

### ISSUE THREAD

**Issue by rtfeldman** [avh4/elm-format#114]
When I write `0.01` it gets converted to `1.0e-2` - this definitely reduces code clarity in some cases.

Can it remember what style you used originally and keep that?

**Comment by avh4** [comment]
Yes, but we should agree on a normalized for for e notation:
  - is "e" lowercase or capital?
  - if the exponent is positive, should it show the plus sign?

If there's a standard number formatter for this in haskell, we should try that first and see if what it does is sufficient.

**Comment by rtfeldman** [comment]
I agree, although I don't have strong feelings about `e` notation; mainly I just want `0.01` in the source to output `0.01` rather than changing it to `e` style.

I'd say if Haskell has an easy way, we should just go with that...but if not, let me know, and I'll do some research to justify a particular style.

**Comment by avh4** [comment]
I ended up using printf `%f` and `%e` for the two formats.  Surprisingly, there aren't really any options for changing how the exponents print other than uppercase vs lowercase.

**Comment by avh4** [comment]
Fixed in 5a66553.
