### ISSUE TITLE
Allow starting multiline mode in a different place

### ISSUE THREAD

**Issue by rtfeldman** [avh4/elm-format#115]
Now that I have [elm-check tests in elm-css](https://github.com/rtfeldman/elm-css/blob/master/test/Compile.elm#L73-L89), I have noticed a pattern of wanting to write this:

```elm
    [ suite "rgb"
        [ it "does not warn when everything is valid"
            (\_ -> 0)
            getRgbWarnings
            (tuple3 ( validRgbValue, validRgbValue, validRgbValue ))

        , it "warns for invalid r values"
            (\_ -> 1)
            getRgbWarnings
            (tuple3 ( invalidRgbValue, validRgbValue, validRgbValue ))
```

...but instead only being able to come as close as this:

```elm
    [ (suite "rgb")
        [ (it "does not warn when everything is valid")
            (\_ -> 0)
            getRgbWarnings
            (tuple3 ( validRgbValue, validRgbValue, validRgbValue ))
        , (it "warns for invalid r values")
            (\_ -> 1)
            getRgbWarnings
            (tuple3 ( invalidRgbValue, validRgbValue, validRgbValue ))
```

The removed blank line would be addressed by https://github.com/avh4/elm-format/issues/97 but the mandatory parentheses would remain.

elm-css itself [has a similar problem](https://github.com/rtfeldman/elm-css/blob/master/test/CompileFixtures.elm#L32-L64): I want to write this...

```elm
dreamwriter : Stylesheet
dreamwriter =
  stylesheet
    { name = "dreamwriter" }
    [ each [ html, body ]
        [ width (pct 100)
        , height (pct 100)
        ]

    , (.) Hidden
        [ (display none) |> important ]

    , (#) Page
        [ width (pct 100)
        , height (pct 100)
        , color pageDefaultText
        ]
    ]
```

...but instead must write this:

```elm
dreamwriter : Stylesheet
dreamwriter =
  stylesheet
    { name = "dreamwriter" }
    [ (each [ html, body ])
        [ width (pct 100)
        , height (pct 100)
        ]
    , ((.) Hidden)
        [ (display none) |> important ]
    , ((#) Page)
        [ width (pct 100)
        , height (pct 100)
        , color pageDefaultText
        ]
    ]
```

It seems like "all in one line" or "break after the function itself" for function application is too black-and-white for a common DSL use case.

Allowing the end user to "break" (and from then on be in multiline mode) after 0 or more arguments have been passed to the function (instead of always after 0 as it currently stands) would make using DSLs like this much easier.

For example:

```elm
-- currently allowed
foo
  bar
  baz
  qux

(foo bar)
  baz

-- proposed to be additionally allowed as well
foo bar
  baz
  qux

foo bar baz
  qux
```

I think only allowing one "break" per function application chain (after which the remaining arguments are multiline) would be reasonable.

**Comment by avh4** [comment]
Would only allowing the first argument on the same line be sufficient?

**Comment by rtfeldman** [comment]
@avh4 For my use case, definitely so!

**Comment by avh4** [comment]
What if the first argument always went on the same line? (assuming the first argument was not a multi-line expression)

**Comment by rtfeldman** [comment]
Hm, I suspect that would be weird.

```elm
Declaration.StyleBlock
  (combineSelectors first selector)
  (List.map (combineSelectors selector) others)
  properties
```

vs.

```elm
Declaration.StyleBlock (combineSelectors first selector)
  (List.map (combineSelectors selector) others)
  properties
```

I think the former is easier to read in this case, whereas in the DSL case the latter would be.

**Comment by rtfeldman** [comment]
Just ran into wanting this in a non-DSL context.

What I wanted to write:

```elm
String.join "\n\n"
  [ charsetToString charset
  , String.join "\n" (List.map importToString imports)
  , String.join "\n" (List.map namespaceToString namespaces)
  , prettyPrintDeclarations declarations
  ]
```

What I wrote to work around it:

```elm
(String.join "\n\n")
  [ charsetToString charset
  , String.join "\n" (List.map importToString imports)
  , String.join "\n" (List.map namespaceToString namespaces)
  , prettyPrintDeclarations declarations
  ]
```

Definitely would have preferred the first! :smile_cat:

**Comment by rtfeldman** [comment]
I'm noticing a pattern. Maybe the "break" should always be at the first multiline expression. Examples:

```elm
-- I indicated that I want multiline mode by putting a newline in, so keep it the same.

String.join
  "\n\n"
  [ foo
  , bar
  ]

-- Output:

String.join
  "\n\n"
  [ foo
  , bar
  ]
```

```elm
-- I used no newlines until I hit the first multiline expression
-- so interpret that as "stick to single line until the first multiline expression"

String.join "\n\n"
  [ foo
  , bar
  ]

-- Output:

String.join "\n\n"
  [ foo
  , bar
  ]
```

```elm
-- I used no newlines at all, so just like last time, interpret that as
-- "stick to single line until the first multiline expression" - which never comes,
-- so stay single line the whole way

String.join "\n\n" [ foo, bar ]

-- Output:

String.join "\n\n" [ foo, bar ]
```

```elm
-- I use multiline expressions in both positions, so set the "break" spot right away
List.append [
  foo,
     bar ]
  [ baz
  , qux
  ]

-- Output:

List.append
  [ foo
  , bar
  ]
  [ baz
  , qux
  ]
```

**Comment by rtfeldman** [comment]
So I've noticed a pattern in how I've been writing things lately, and I think I'm on board the "first argument always goes on the same line" train given one modification. This proposal would maintain the current "your options are single-line or multi-line, and you have no flexibility beyond that" policy.

Earlier I gave this as a motivation for allowing the current "first argument on the next line" behavior:

```elm
Declaration.StyleBlock
  (combineSelectors first selector)
  (List.map (combineSelectors selector) others)
  properties
```

However, lately I've been considering expressions like this as bloated and in need of refactor.

Today I think I'd extract the sub-expressions in the above into named expressions:

```elm
let
  firstSelector =
    combineSelectors first selector 

  otherSelectors =
    List.map (combineSelectors selector) others 
in
  Declaration.StyleBlock firstSelector otherSelectors properties
```

This is more lines of code, but I think it's easier to follow—and that's the right tradeoff to make. In that light, having elm-format encourage this by making the original code look "wrong" seems like a feature.

Having said that, I do think the current formatting should persist if the first argument is multi-line, e.g.

```elm
ul
  [ class "foo"
  , id "bar"
  ]
  [ li [] [ text "one" ] 
  , li [] [ text "two" ]
  , li [] [ text "three" ]
  ]
```

If the first argument there (`class`, `id`, etc) were forced onto the first line, I think that would look awkward. However, putting the first argument on its own line whenever that first argument is multiline solves this case, and it does so without introducing additional flexibility to the end user.

In this world, it seems like there are three styles that make sense:

1) All one line (using `let` to extract sub-expressions if necessary)
2) Multiline function call with multiline first argument (works like it does today)
2) Multiline function call with single-line first argument (first argument stays on the same line)

Thoughts @avh4?

**Comment by avh4** [comment]
So you can never have the first argument on a new line unless that argument is a multiline expression?  That sounds like it will be annoying, but we can try it.

**Comment by avh4** [comment]
Here's the diff: https://github.com/avh4/elm-format/compare/first-args  @rtfeldman

**Comment by rtfeldman** [comment]
I'd rate these changes as either "fine" or "significantly better."

I think it's worth trying, to see how it feels in practice!

**Comment by avh4** [comment]
Okay, I'm going to merge this.  Added https://github.com/avh4/elm-format/issues/163 to follow up.

**Comment by avh4** [comment]
Fixed in 42cd986.

**Comment by glenjamin** [comment]
Is this the best place to ask about still allowing the first argument to sit on its own line?

Having the first argument on the same line as the function implies that the first argument is somehow more important - which in this example is not the case:

```
initialWindowSize : Cmd Msg
initialWindowSize =
    Task.perform (\_ -> Debug.crash "no window?")
        WindowSize
        Window.size
```

Is there any better way to write this?

**Comment by avh4** [comment]
@glenjamin I think I agree.  This should be a new issue.

**Comment by glenjamin** [comment]
Ok, opened as #178
