### ISSUE TITLE
Hexadecimal notation for integers should be retained

### ISSUE THREAD

**Issue by norru** [avh4/elm-format#118]
this

     else if (c <= 0x07ff) then 
         [ ((c `shiftRight` 6) `and` 0x1f) `or` 0xc0
         , (c `and` 0x3f) `or` 0x80 
        ]

becomes this

        else if (c <= 2047) then
            [ ((c `shiftRight` 6) `and` 31) `or` 192
            , (c `and` 63) `or` 128
            ]

and many more

**Comment by avh4** [comment]
Fixed in 349135.
