### ISSUE TITLE
Replace regex-applicative with better code

### ISSUE THREAD

**Issue by avh4** [avh4/elm-format#123]
See #121, #122.  The approach in #122 is more performant, as noted below, but the code was harder to understand.  An ideal solution is one that is easy-to-read, fast, and has minimal external dependencies.  If a better solution can be found, please submit a PR!

@ento wrote:

> I took some benchmarks, and splitting is consistently more performant than regex, by a factor of 2-10. (but not sure if it matters within the whole scheme of things, i.e. how much time it's going to take up within a single elm-format run)
> 
> 'x' \* n + triple quotes (max n: 10000, order of magnitude: 10ms)
> '"' \* n (max n: 10, order of magnitude: 10 microseconds)
> 'x' \* 10000 with randomly inserted triple quotes \* n (max n: 1000, order of magnitude: 10ms)
> 
> benchmark code: https://gist.github.com/ento/6b544b06f5032e55eca8

**Comment by ento** [comment]
Note to future contributor: this might just be about making #122 more idiomatic Haskell.

**Comment by avh4** [comment]
Fixed in b91de6ce...95d598ac
