### ISSUE TITLE
No vertical spacing after port declarations

### ISSUE THREAD

**Issue by nphollon** [avh4/elm-format#131]
If I run elm-format on the following snippet:

    port a : Signal Int

    main : Html
    main = div [] []

I get:

    port a : Signal Int
    main : Html
    main =
      div [] []

The removal of empty lines between `port` and `main` seems like a bug. I think there ought to be 2 empty lines, as there are between function declarations.

**Comment by avh4** [comment]
Fixed in d63a2f7.  Thanks for the report and reproducible example!
