### ISSUE TITLE
UTF-8 encoded no break space is converted to "\xA0" with elm-format.

### ISSUE THREAD

**Issue by rluiten** [avh4/elm-format#132]
I have an identifier that contains no break space in my code. its called `nbsp` it is stored as a utf-8 character in the source file this allows to me to output them as needed with html.

Grabbed and built elm-format it earlier today about 2 hours a back and built it locally.
I tried out current elm-format "elm-format 0.3.0-alpha-dev"  and it converts my declaration to

```
nbsp = "\xA0"
```

Which makes sense and is what I wanted to do to start with in my source.

But the problem is this does not compile with elm-compiler 0.16 - at least it doesn't on my system which is windows 7 64 bit.

**Comment by avh4** [comment]
I reported a bug on elm-compiler.  In the meantime, I will special-case `\xA0` to not be converted to an escape sequence.

**Comment by avh4** [comment]
Fixed in 816b560.
