### ISSUE TITLE
Possibly weird formatting

### ISSUE THREAD

**Issue by gyzerok** [avh4/elm-format#140]
Here is real code from take-home I am working on

```elm
stylePath : Style -> String
stylePath tag =
  "/styles/" ++
    case tag of
        AdminStyle ->
          "admin.css"

        SignupStyle ->
          "signup.css"
```

After formatting it become

```elm
stylePath : Style -> String
stylePath tag =
  "/styles/"
    ++ case tag of
        AdminStyle ->
          "admin.css"

        SignupStyle ->
          "signup.css"
```

which looks weird to me.

If it's normal, just close this issue.

**Comment by mgold** [comment]
Looks odd to me. Infix ops are one of the few cases in which things are frequently "weird".

**Comment by avh4** [comment]
What you are seeing is currently expected given the simple rule for formatting infix operators.

I'm going to close this one.  If there's a proposed change for how to handle infix operators, we would need to consider the many different ways infix operators are commonly used.  If someone wants to make a proposal, please open a new issue for that.

Thanks!
