### ISSUE TITLE
Interactive warning when formatting a file in place

### ISSUE THREAD

**Issue by avh4** [avh4/elm-format#15]
`elm-format path/MyFile.elm` should produce the following prompt:

```
This will overwrite the following files to use Elm’s preferred style:

  path/MyFile.elm

This cannot be undone! Make sure to back up these files before proceeding.

Are you sure you want to overwrite these files with formatted versions? (y/N)
```

`elm-format --yes path/MyFile.elm` or `elm-format path/MyFile.elm --yes` should overwrite the file without prompt.

**Comment by avh4** [comment]
As a further note, the prompts should feel consistent with prompts used in `elm-package`, code for reference: https://github.com/elm-lang/elm-package/blob/master/src/Install.hs

**Comment by Janiczek** [comment]
Oh, amazing - I had this implemented somehow but this is much nicer and
more polished (Cmd.yesOrNo etc.). Will update to that style before creating
a pull request.
