### ISSUE TITLE
colons in record values are transformed to equals

### ISSUE THREAD

**Issue by avh4** [avh4/elm-format#150]
```elm
foo = { x : Int, y : Int }
```

should become

```elm
foo = { x = Int, y = Int }
```

when formatted

**Comment by mgold** [comment]
What's the desired behavior? It's actually kind of nice that elm-format corrects a common mistake (if you're coming from JS). Of course, this only works because the first version is never valid.

**Comment by avh4** [comment]
Fixed in fbb5b54.  The result is that if you use `=` or `:` incorrectly in a record type or record value, elm-format will correct it.  We'll try this out in 0.3.0-alpha and see if there are any problems with it.
