### ISSUE TITLE
Multiline comment "trick" not fully supported

### ISSUE THREAD

**Issue by rohanorton** [avh4/elm-format#154]
Hi there,

There's an inconsistency with how multiline comments are handled here and a recommendation in the [docs](http://elm-lang.org/docs/syntax#comments)

They suggest that you can do the following "trick":
```elm
{--}
foo = 1
--}
```
This works great with elm-format, but if reinstate the comment like this:
```elm
{--
foo = 1
--}
```
elm-format changes it to
```elm
{- -
foo = 1
-
-}
```
Which removes the ability to quickly comment / de-comment the code.

(Running 0.2-alpha)

**Comment by avh4** [comment]
This looks like a good thing to support.  Thanks for reporting!

**Comment by avh4** [comment]
Fixed in a26b347.

**Comment by boxed** [comment]
I'm using elm-format 0.7.0exp and this is broken again :(
