### ISSUE TITLE
contents of comment block indenting deeper every call to elm-format

### ISSUE THREAD

**Issue by justgage** [avh4/elm-format#157]
I don't know about others but I found that there are strange behaviors of comment blocks inside of maps. 

for instance this constantly indents the contents of the comment block:
```elm
module Main (..) where


main =
  2


map =
  { a =
      {}
      {-
                  % This will travel right every time I elm-fromat ->

      -}
  }
```

It seems this only happens when there's a blank line before -}.

It's even worse if there's a extra comma after the `a = {}`. In this case it deletes the entire comment block like so:

```elm
module Main (..) where


main =
  2


map =
  { a =
      {}
  }
```

It seems elm-format has grown a mind of it's own and has decided that this code is self documenting ;)

**Comment by avh4** [comment]
I haven't seen the comma thing before, thanks for reporting!  I've created https://github.com/avh4/elm-format/issues/159 for that.

The traveling comment issue sounds the same as https://github.com/avh4/elm-format/issues/90 and will be fixed in the next release (and is currently fixed on master)

**Comment by justgage** [comment]
Awsome, maybe I'll have to switch to master.
