### ISSUE TITLE
Badly formatted record causes comments to be deleted

### ISSUE THREAD

**Issue by avh4** [avh4/elm-format#159]
From https://github.com/avh4/elm-format/issues/157

``` elm
map =
  { a = (),{-COMMENT-} }
```

when formatted, the comment is deleted, but should not be.

**Comment by gyzerok** [comment]
Is there a description of what you expect as an output for such cases?

**Comment by avh4** [comment]
The comma should be removed, but the comment should remain.

**Comment by Janiczek** [comment]
It seems like longterm it should just format it without removing the comma, though? If you format the file "mid-thought" and it removes what you wrote...

Maybe it is OK to remove the comma though - if users expect it "normalizes" code a bit. It's all about expectations :)

**Comment by avh4** [comment]
(I expect it'll be easier to remove the comma because the parsed AST can't actually represent a trailing comma without another term :) )

**Comment by avh4** [comment]
This is fixed in 95d598ac...6226206f  (trailing commas in records are now disallowed, so files containing them will no longer be formatted by elm-format.
