### ISSUE TITLE
Allow end-of-line comments

### ISSUE THREAD

**Issue by avh4** [avh4/elm-format#162]
A `--` comment at the end of a line should be attached to the preceding token instead of to the subsequent token.

 - [x] after record fields in types
 - [x] after record fields in expressions
 - [x] after values in list expressions
 - [x] after values in tuple expressions
 - [x] after entries in tuple types
 - [x] union type definitions
 - [x] after record fields in record updates
 - [x] after record fields in record extension types
 - [x] in function types
 - [x] in binary operator expressions
 - [x] in cons patterns
 - ? tag arguments in types (`Tag --z\n a --x\n b --y\n`)
 - ? case branches
 - ? if/else branchs
 - ? let definitions
 - ? top-level definitions

**Comment by willnwhite** [comment]
Is that this?
![screen shot 2016-06-23 at 22 20 12](https://cloud.githubusercontent.com/assets/8081877/16320666/e6c20f7c-3990-11e6-8b4d-6fe83281ea63.png)

**Comment by avh4** [comment]
yep, the goal is to get the uid field and comment to all stay on one line.

**Comment by avh4** [comment]
Initial attempt implemented in a49548470e717f48a61dccde5278bc5b514d7bb8...07afe63d0814c8f7ba556da901967de564c76416

**Comment by avh4** [comment]
Implemented for union type declarations in 080cb9a2...f9e2f8c8

**Comment by avh4** [comment]
Implemented for binary operators, function types, and cons patterns in 515ca02a...3532eb66

**Comment by avh4** [comment]
I'm still debating whether it's good to allow this in all the places I added it for... For instance, having end-of-line comments after items in a list literal: is that a place where we should instead be encouraging refactoring?

In any case, all the TODOs for this have been implemented.  Marking as resolved.
