### ISSUE TITLE
Proposal: Add a --verify flag

### ISSUE THREAD

**Issue by rtfeldman** [avh4/elm-format#168]
## Motivation

I have open-source projects on which I use elm-format. Sometimes I merge PRs from people who don't use elm-format, only to discover later that I've ended up with elm-format diffs. These are annoying, especially if I've already started coding and don't realize I have diffs to clean up (ideally in a separate commit), at which point I have to double back and fix them before proceeding with what I actually want to be doing.

It would be better to be able to handle these proactively, by adding something like an `elm-format --verify` step to my Travis config which would fail the build if elm-format would produce any diffs with the current file structure.

## Proposed Change

Add a `--verify` flag to the CLI. When set, instead of generating any actual files, elm-format instead compares what it intends to generate with what's currently on the file system.

The CLI output is either:
* A success message and exit code 0 if there are no diffs
* A list of files that have diffs and a nonzero exit code. (Textual diffs do not seem useful, as no matter what, the prescription is to run elm-format on those files and end up with zero diffs.)

**Comment by avh4** [comment]
Fixed in https://github.com/avh4/elm-format/commit/5dfe7edf313691c4cc359ab68168e7fd175db302 and https://github.com/avh4/elm-format/commit/5dfe7edf313691c4cc359ab68168e7fd175db302

**Comment by avh4** [comment]
@rtfeldman Here is what's implemented:

Docs:
```
--validate               Check if files are formatted without changing them.
```

Output of `elm-format file.elm --validate` when file is formatted (exit code 0):
```
Processing file file.elm
```

Output of `elm-format file.elm --validate` when file is not formatted (exit code 1):
```
Processing file file.elm
File would be changed file.elm
```

I think the output format can/should be cleaned up a bit, but that should probably be a separate issue.

**Comment by rtfeldman** [comment]
Awesome!!! 🎉 🎉 🎉 

Can't wait to integrate this into my builds! 😸

**Comment by harrysarson** [comment]
Is worth flagging up that if anyone is running elm-format with the `--validate` flag in travis CI then it is well worth using the solution mentioned in https://github.com/elm/compiler/issues/1473#issuecomment-245704142 to speed up the linting which will otherwise take an exceptionally long time.
