### ISSUE TITLE
Support for Elm 0.17

### ISSUE THREAD

**Issue by liamcurry** [avh4/elm-format#171]
Elm 0.17 was just released and slightly changes the syntax for module declarations. 

See:

- [new `where` and `exposing` syntax](http://elm-lang.org/docs/syntax#modules)
- [`effect` module](https://raw.githubusercontent.com/elm-lang/geolocation/1.0.0/src/Geolocation.elm)
- [`port` module](https://evancz.gitbooks.io/an-introduction-to-elm/content/interop/javascript.html)

Looks like files using the new 0.17 syntax don't work with elm-format at the moment.

**Comment by avh4** [comment]
These issues have all been fixed on master.  I am expecting to release 0.3.0-alpha tomorrow for Elm-0.17.

**Comment by liamcurry** [comment]
@avh4 thank you!
