### ISSUE TITLE
--output flag doesn't work with nonexistant paths on windows

### ISSUE THREAD

**Issue by AdirShemesh** [avh4/elm-format#174]
elm-format File.elm --output [some_filename]
returns -
elm-format: [some_filename]: openBinaryFile: does not exist (No such file or direcory)
on windows

**Comment by AdirShemesh** [comment]
actually it only fails when you specify:  --output /subfolder/file

**Comment by avh4** [comment]
hmm, what about `--output \subfolder\file` ?

**Comment by AdirShemesh** [comment]
gives the same output

**Comment by Janiczek** [comment]
Shouldn't that be `--output subfolder\file` (no leading slash)? or is it there just to indicate the subfolder presence?

**Comment by AdirShemesh** [comment]
you're right, subfolder/file and subfolder\file work

**Comment by AdirShemesh** [comment]
(but only if the subfolder already exists)

**Comment by avh4** [comment]
hmm, okay, so this came up in the context of the atom elm-format plugin, which apparently wants to write the output file to `/tmp/something.elm` .. need to investigate that a bit more and make sure it's asking elm-format to do something sane.

**Comment by avh4** [comment]
Looks like this is a bug in the elm-format plugin--it is assuming that `/tmp` exists which is not generally true on Windows, so it's asking elm-format to write the file to a directory that doesn't exist.

See https://github.com/triforkse/atom-elm-format/pull/6

**Comment by benjick** [comment]
I've merged and published triforkse/atom-elm-format#6 now

**Comment by avh4** [comment]
Should be fixed in atom-elm-format 1.2.1.  No change to elm-format necessary.  Please reopen if that's not the case.  Thanks for reporting this!
