### ISSUE TITLE
Multiline string removes backslash \

### ISSUE THREAD

**Issue by proProbe** [avh4/elm-format#175]
Im working with htmltags right now in the form of `<meta property=\"og:title\" content=\"cool title\"`
The `\` are there as Http.getString formats the html to string and adds `\`.

A multiline string similar to
```
"""
    <meta property=\"og:title\" content=\"cool title\" />
    <meta property=\"og:image\" content=\"http://awesomeness\" />
"""
```
Will when formatted turn into:
```
"""
    <meta property="og:title" content="cool title" />
    <meta property="og:image" content="http://awesomeness" />
"""
```
Not sure if its intentional?

**Comment by avh4** [comment]
Yes, this is currently expected, since `"` does not need to be escaped in multiline strings, and

```
"""
\"
"""
```
is equivalent to 
```
"""
"
"""
```

If you need the backslash to actually be in the string, then you need to escape the backslash.

**Comment by proProbe** [comment]
That makes sense. Apparently when messing around a bit more, a multilinestring actually adds backslash to `"` automatically
```
    """
      <meta class="a-1" property="og:title" content="cool title"     />
    """
```
gives:
```
"<meta class=\"a-1\" property=\"og:title\" content=\"cool title\"   />"
```
So problems solved :)
