### ISSUE TITLE
Arch Linux packages

### ISSUE THREAD

**Issue by mattjbray** [avh4/elm-format#177]
Just to let you know, I've created packages in the Arch User Repository for Arch users:

https://aur.archlinux.org/packages/elm-format-0.16-bin/
https://aur.archlinux.org/packages/elm-format-0.17-bin/

I'll leave it up to you whether to mention them in the README, or just stick to the existing installation methods.

Thank you for elm-format!

**Comment by avh4** [comment]
Thanks!  What will need to be done to keep these packages up-to-date?

**Comment by mattjbray** [comment]
The update process is trivial - (1) bump a version number, (2) re-generate the metadata, (3) git commit and push.

I'm watching the `elm-format` repo and I will update the packages as soon as I am able when a new release comes along. If you want you could add a step to your release process to flag these packages as out-of-date using the links above, which will notify me directly.

If you would rather take over the packages, I can add you as the maintainer and give you instructions for updating them.

**Comment by avh4** [comment]
Cool, I'm happy to have you own it for now.  If you have any scripts or checklist for when you do the release, it would be great to have that merged into the elm-format repo for future reference.

**Comment by mattjbray** [comment]
Great, next time there is a release I'll document the process and send a PR.
