### ISSUE TITLE
Do something decent with `andThen` \x -> `andThen` ... pattern

### ISSUE THREAD

**Issue by avh4** [avh4/elm-format#187]
From https://github.com/avh4/elm-format/issues/33#issuecomment-167204434

Not sure if this belongs here, but I had a block of code like this:

```
person : Random.Generator Person
person =
    sex `andThen` \s ->
    weight `andThen` \w ->
    height `andThen` \h ->
    Random.Extra.constant (Person s w h)
```

and elm-format turned it into this:

```
person : Random.Generator Person
person =
    sex
        `andThen` \s ->
                    weight
                        `andThen` \w ->
                                    height
                                        `andThen` \h ->
                                                    Random.Extra.constant (Person s w h)
```

Except it was even longer. I don't feel like this is a good formatting style for the andThen patterns that we have in some modules.

**Comment by Apanatshka** [comment]
Perhaps you can special-case an expression that ends in a lambda?

**Comment by avh4** [comment]
Yeah, I was thinking about that.  If we do that, one question is can/should the parens always be dropped?

**Comment by Apanatshka** [comment]
Minimal parentheses sounds like the easiest normalisation. In this case it also seems the most natural thing to do. I guess we need another example of code that takes a function as final argument to see if this is always the best style.

**Comment by akbiggs** [comment]
IMO this shouldn't have a special case. Each one of these is opening up a new lambda that has additional variables in scope -- nesting them at the same level of indentation allows people to write misleading code like this:

```
size `andThen` \s ->
velocity s `andThen` \vel ->
Model s vel
```

where it doesn't seem like the second line should have any dependencies on the first line since there's no assignment and no indentation, but the first line is introducing a new scope with new dependencies.

If you have a bunch of unrelated dependencies, use the `Random.map` function to handle them independently of each other, so only one new scope needs to be created.

**Comment by avh4** [comment]
https://github.com/avh4/elm-format/compare/e205d49...c3e672b#diff-e2027295cb51a51f5485562ee53153d4 improves this somewhat.  Does that improve things enough or does more need to be done?

**Comment by gyzerok** [comment]
I personally would like it to behave as you described in the first post. We do not have any alternative to a do notation right now so we have to write it in this way. Why not in a nested way? I feel more cognitive pressure trying to read nested ones. Do you feel the same?

```elm
person : Random.Generator Person
person =
    sex `andThen` \s ->
    weight `andThen` \w ->
    height `andThen` \h ->
    Random.Extra.constant (Person s w h)
```

**Comment by avh4** [comment]
The formatting in 0.4.0-alpha will be:

```elm
person : Random.Generator Person
person =
    sex
        `andThen`
            \s ->
                weight
                    `andThen`
                        \w ->
                            height
                                `andThen`
                                    \h ->
                                        Random.Extra.constant (Person s w h)
```

Which is at least less indentation and more regular indentation that what was previously done.  If more changes are desired, please open a new issue.
