### ISSUE TITLE
GHC 8 workaround

### ISSUE THREAD

**Issue by ilovezfs** [avh4/elm-format#188]
To get elm-format building under GHC 8.0.1 for Homebrew (we only typically support the latest GHC), I've needed to add a "cabal.config" file at the root of the package containing "allow-newer: aeson,base,transformers", at which point everything builds as expected. Without this, I get

```
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: elm-format-0.3.0 (user goal)
trying: transformers-0.5.2.0/installed-0.5... (dependency of
regex-applicative-0.3.3)
next goal: optparse-applicative (dependency of elm-format-0.3.0)
rejecting: optparse-applicative-0.12.1.0, optparse-applicative-0.12.0.0
(conflict: elm-format => optparse-applicative>=0.11 && <0.12)
rejecting: optparse-applicative-0.11.0.2, optparse-applicative-0.11.0.1,
optparse-applicative-0.11.0 (conflict: transformers==0.5.2.0/installed-0.5...,
optparse-applicative => transformers>=0.2 && <0.5)
rejecting: optparse-applicative-0.10.0, optparse-applicative-0.9.1.1,
optparse-applicative-0.9.1, optparse-applicative-0.9.0,
optparse-applicative-0.8.1, optparse-applicative-0.8.0.1,
optparse-applicative-0.8.0, optparse-applicative-0.7.0.2,
optparse-applicative-0.7.0.1, optparse-applicative-0.7.0,
optparse-applicative-0.6.0, optparse-applicative-0.5.2.1,
optparse-applicative-0.5.2, optparse-applicative-0.5.1,
optparse-applicative-0.5.0, optparse-applicative-0.4.3,
optparse-applicative-0.4.2, optparse-applicative-0.4.1,
optparse-applicative-0.4.0, optparse-applicative-0.3.2,
optparse-applicative-0.3.1, optparse-applicative-0.3.0,
optparse-applicative-0.2.0, optparse-applicative-0.1.1,
optparse-applicative-0.1.0, optparse-applicative-0.0.1 (conflict: elm-format
=> optparse-applicative>=0.11 && <0.12)
Dependency tree exhaustively searched.
```

**Comment by avh4** [comment]
Thanks, what does `allow-newer` do?  And will this need to remain permanently, or is this expected to be unnecessary at some point in the future (maybe after packages get upgraded?)?

**Comment by ilovezfs** [comment]
allow-newer overrides the `< p` or `<= p` for the listed packages, or for all packages if you put `allow-newer: True`. It's the `cabal.config` equivalent of the `--allow-newer=…` and `--allow-newer` command line switches.

The override applies to elm-format and all of its dependencies, so it can go away as soon as all of the relevant `foo.cabal` files have been updated by their respective developers.

An alternative approach is to patch each `foo.cabal` one at a time, and use `cabal sandbox add-source` which is more involved, but also more precise. For an example of more involved patching, see
https://github.com/Homebrew/homebrew-core/blob/592971be0aa3c986f39e8bde70928ed61db29001/Formula/pandoc-crossref.rb#L24-L51

**Comment by avh4** [comment]
elm-format has been updated to use `stack`, and will use ghc-8.0.1 when building  Please re-open if that does not address your concerns.
