### ISSUE TITLE
Implement "Feldman's Rule" of inner spaces

### ISSUE THREAD

**Issue by avh4** [avh4/elm-format#20]
From #7.

> Since we need to pick one to start, I'd say let's start with "spaces if there are commas," in other words:
> 
>     ( foo, bar )
>     (foo bar)
>     (foo == bar)
> ...or perhaps more precisely "spaces if there could be commas," so in other words:
> 
>     import Foo exposing ( bar )
>     import Bar exposing ( baz, qux )
> I've never tried that style with imports, but at first glance I like how it looks!

**Comment by Apanatshka** [comment]
Off topic: Haha, I can totally see a wikipedia entry in the near future about this. 

> Feldman's rule for inner spaces, a seminal rule for code style, was first proposed by Richard Feldman. The first automated implementation was in the elm-format tool, a code formatting tool for the popular Elm programming language. Feldman was involved in the development of the tool and first proposed the rule in online discussions. 
The particularly interesting property of this rule is the almost undisputed acceptance[citation needed], where most code style rules are considered ...

**Comment by avh4** [comment]
@rtfeldman What about exposing constructor types?

```elm
module AllSyntax ( fn, tuple, Type, Union ( A, B, C ), Union2 (..) ) where
```

**Comment by avh4** [comment]
I think it's better without spaces in import/module statements

**Comment by rtfeldman** [comment]
Yeah I'll agree with that. I'm sold on "no spaces in import/module statements."

**Comment by avh4** [comment]
@rtfeldman Here's another I'm not sure if you thought of:  pattern matches

```elm
patternAlias ({ x, y } as r) ( a, { b } as r' ) =
    r.x == y
```

I would not normally have put spaces in there, but since it is actually about tuples and records, it seems like it ought to be consistent with tuple and record values.

**Comment by rtfeldman** [comment]
I actually would put spaces there (for consistency), but ymmv. :)

**Comment by avh4** [comment]
Finished in 5f21e15
