### ISSUE TITLE
Empty switch case crashes elm-format on save

### ISSUE THREAD

**Issue by willnwhite** [avh4/elm-format#204]
![screen shot 2016-06-18 at 12 44 41](https://cloud.githubusercontent.com/assets/8081877/16170652/8e037dea-3552-11e6-9fa9-3a0430c44cef.png)

**Comment by rundis** [comment]
Elm format doesn't crash :-) IMHO I think it's fine that elm-format reports that there is an error in the code that makes in unreliable/impossible to format the file deterministically. Atom chooses to display a red error message which is fair enough I suppose. 

@willnwhite What would you expect to happen ? Silent failiure ? best effort formatting  ?

**Comment by willnwhite** [comment]
I would expect nothing to happen. No formatting is needed.

**Comment by rundis** [comment]
Well elm-format can't know that without parsing the code. The code as it stands is invalid. That's what it's reporting back to Atom. Atom chooses to display that fact. If you are unhappy with that, maybe it would be more appropriate to raise that in the issue tracker for the relevant Atom plugin.

**Comment by avh4** [comment]
elm-format prints the syntax error to the console in this case.  So yes, this is an issue for the atom plugin.

But I would like to provide guidelines for plugin developers.  See https://github.com/avh4/elm-format/issues/104  Is there we can add as guidance on how plugins should handle the case where there is a syntax error?

**Comment by avh4** [comment]
This was an issue with the atom plugin, not with elm-format.
