### ISSUE TITLE
elm-make does not error, but elm-format cannot parse

### ISSUE THREAD

**Issue by mordrax** [avh4/elm-format#205]
I have no idea what's causing this as it was working before a namespace refactor (moving files around). But since then, elm-format chokes on this line:
https://github.com/mordrax/cotwelm/commit/197586dbfb31dba082ff3b27b63646d4687f18a9#diff-375f6bd477ce0b3d1df0469b29508f75R197

saying:
```
 ran into something unexpected when parsing your code!

196│                     Equipment.ItemMsg Item.TypeDef.Ok ->
                         ^
I am looking for one of the following things:

    end of input
    whitespace
```

The type is exposed and known, the program is working as expected, I'm not sure what's going on to create a simpler example of this error...

Taking that case out (there's a catch all at the bottom) fixes the elm-format issue

**Comment by mordrax** [comment]
Don't know if this'll help narrow down the issue, but I worked out that the second part of the pattern match was causing the issue, so changing the case to tbe below one worked!
```
                    Equipment.ItemMsg a ->
                        case a of
                            Item.TypeDef.Ok ->
                                success

                            _ ->
                                Result.Err ("Dropping into pack with unhandled item msg" ++ (toString a))
```

**Comment by robertjlooby** [comment]
I ran in to a similar issue and came up with an SSCCE:

```diff
module Main exposing (..)

update : Msg -> Model -> ( Model, Cmd Msg )
update msg model =
    case msg of
-        Other A ->
+        Other Other.A ->
            model ! []
```

Though both are invalid and and won't compile, the red will format fine, while the green will not.

Even with valid code that will compile, it seems like matching an "inner" part of a union type with a namespaced type breaks elm-format.

**Comment by mordrax** [comment]
@robertjlooby That is interesting.
I had also tried aliasing the namespace or making it implicit/explicit to no avail i.e
```
import Item.TypeDef as ItemTypeDef exposing (..)

ItemMsg ItemTypeDef.Ok ->
    success
```

**Comment by avh4** [comment]
I think this is the same as https://github.com/avh4/elm-format/issues/184 which is fixed on master, but sorry, I haven't made a new release yet.  (I hopefully will have 0.4.0-alpha released this weekend.)

The workaround for the original would be to put parens around qualified type constructors that are parameters in the pattern match, like this:
```elm
   Equipment.ItemMsg (Item.TypeDef.Ok) ->
```

If you are using elm-0.16, you must put parentheses there due to a compiler bug.  If you are using elm-0.17, then it should work fine without the parens once I release elm-format-0.4.0-alpha.

**Comment by mordrax** [comment]
Ah ok, I see that now. I totally missed your workaround in the other issue, have put parens and it formats fine :) Thanks!

**Comment by avh4** [comment]
0.4.0-alpha is not released with this fix https://github.com/avh4/elm-format#installation-
