### ISSUE TITLE
Package elm-format for Nix

### ISSUE THREAD

**Issue by tiziano88** [avh4/elm-format#208]
This is more of an issue for https://github.com/NixOS/nixpkgs, but I'm opening it here to avoid duplicate efforts in case more people wish to do this.

See https://nixos.org/wiki/Create_and_debug_nix_packages for some details. I may start taking a look at it at some point next week.

**Comment by nicknovitski** [comment]
[This has been done](https://github.com/NixOS/nixpkgs/blob/6ae57b1b634d2145f72c1742685695e7192102ba/pkgs/development/compilers/elm/packages/elm-format.nix). 😃

**Comment by avh4** [comment]
Someone seems to be doing this, and the nix package is currently one of the fastest to get updated when there's a new release. :)  Thanks!
