### ISSUE TITLE
Should single-line `if` expressions be allowed?

### ISSUE THREAD

**Issue by gyzerok** [avh4/elm-format#209]
Following code

``` elm
isPalindrome : List comparable -> Bool
isPalindrome list =
    List.map2 (,) list (List.reverse list)
        |> List.foldl
            (\( x, y ) acc -> if x == y then acc else False)
            True
```

turns to this

``` elm
isPalindrome : List comparable -> Bool
isPalindrome list =
    List.map2 (,) list (List.reverse list)
        |> List.foldl
            (\( x, y ) acc ->
                if x == y then
                    acc
                else
                    False
            )
            True
```

What do you think about it guys?

**Comment by rtfeldman** [comment]
I guess this reduces to "should single-line *if-expressions* be allowed?"

I'd be fine with that. I've used them before, and they didn't seem particularly more prone to getting out of hand than any other kind of expression.

**Comment by avh4** [comment]
I think this is worth considering.  Though for the example given, I would tend to use `let`:

```elm
isPalindrome list =
    let
        step ( x, y ) acc =
            if x == y then
                acc
            else
                False
    in
        List.map2 (,) list (List.reverse list)
            |> List.foldl step True
```

I'd love to see a few more examples from real code.  Are inline lambdas the main place where this would be useful?

**Comment by gyzerok** [comment]
I'm right now on road of implementing [99 Haskell problems](https://wiki.haskell.org/H-99:_Ninety-Nine_Haskell_Problems) in Elm. And this is just a code for one of those problems. I would try share more examples while moving through this problems.

**Comment by simonewebdesign** [comment]
Here's an example from real code:

``` elm
getAtPath configuration.path model.data
    |> valueToString
    |> (\str ->
            if str == "Yes" ||
               str == "No" then model.translate str else str
        )
```

turns to this:

``` elm
getAtPath configuration.path model.data
    |> valueToString
    |> (\str ->
            if
                str
                    == "Yes"
                    || str
                    == "No"
            then
                model.translate str
            else
                str
       )
```

Definitely seems a bit too aggressive :)

**Comment by gyzerok** [comment]
It looks like here there is no problem with single/multiline if, but rather with boolean expression formatting.

```elm
str
    == "Yes"
    || str
    == "No"
```
This looks weird to me.

**Comment by seanhess** [comment]
I would definitely prefer if/then to be more flexible.

**Comment by Zimmi48** [comment]
I vote for allowing single-line `if then else` expressions. I'm quite annoy to get

    toString points ++ " point" ++ (if points >= 2 then "s" else "")

turned into

    toString points ++ " point"
        ++ (if points >= 2 then
                "s"
            else
                ""
           )
```

There is no specific syntax for ternary conditions in Elm (as in C) so let short `if then else` expressions be.

**Comment by crazymykl** [comment]
Another vote for single-line if. It's much nicer in `let`-bindings, especially since those already make functions very tall.

---

```elm
yesno b =
    if b then "yes" else "no"
```
seems nicer to read than
```elm
yesno b =
    if b then
        "yes"
    else
        "no"
```

**Comment by avh4** [comment]
Evan has requested that `if` expressions have blank lines between the clauses https://github.com/avh4/elm-format/issues/393 which seems to make a single-line version of `if` more desirable.

**Comment by klazuka** [comment]
@avh4 any update on this? The first thing I thought after I saw the blank-line-between-if-clauses in the 0.8.0 changelog was "I hope single-line ifs" are supported.

**Comment by klazuka** [comment]
I just went through my codebase and pulled out some examples:
https://gist.github.com/klazuka/fdd18790ce50ee291a1a210c63ef48f7

After looking at a lot of `if`s in my codebase, it seems to me that the strongest case for single-line `if` is in places like an Html view or an inner declaration in a `let/in` expression. In such cases, multi-line `if` with a blank line before the `else` makes the code too ragged/disconnected/floaty, IMHO.

I was surprised that single-line looked wrong _much_ more often than I expected.

That being said, I think there's still a case for leaving the choice up to the developer. If they leave it all on a single line, then let it be, similar to how function arguments are only pushed out to separate lines if the developer breaks it up into separate lines.

**Comment by klazuka** [comment]
Here's another real-world example I just found in my codebase...

status quo:
```elm
p
    [ style
        [ ( "width", "70%" )
        , ( "padding", "6px" )
        , ( "margin-left", "-6px" )
        , ( "background-color"
          , if isEndUser then
                "#eef3ff"

            else
                "white"
          )
        ]
    ]
    [ text "..." ]
```

single-line variant:
```elm
p
    [ style
        [ ( "width", "70%" )
        , ( "padding", "6px" )
        , ( "margin-left", "-6px" )
        , ( "background-color", if isEndUser then "#eef3ff" else "white" )
        ]
    ]
    [ text "..." ]
```

Single line seems like a much better choice here.

**Comment by ianp** [comment]
I’d love to see `elm-format` get to the point where @evancz & co. could start using it on [elm/core](https://github.com/elm/core), and right now the core libs use single line lambdas and single line ifs in a few places, sometimes even both at the same time! E.g. here [List.elm#L215](https://github.com/elm/core/blob/01a21650a3d9da1f0aeadd71998d37e442a64c34/src/List.elm#L215)

**Comment by ymtszw** [comment]
I had a possibly interesting experience around this.

I also wanted oneline if-then-else since switching relatively short expression was somewhat common in my codebase, especially in views (e.g. just switching color or border style based on activation state.)

But found elm-format does not allow that.
"Well, okay," I thought, discussion is going in this issue anyway. Time will resolve this.

In the mean time, let's just have this to avoid formatting:

```elm
ite : Bool -> a -> a -> a
ite condition then_ else_ =
    if condition then
        then_

    else
        else_
```

... and I used it casually, everywhere, everywhen I thought I wanted oneline logical switch.

However, recently I realized that this helper function actually have an significant flaw: **it eliminates laziness of if-then-else!**

It could be OK if both `then_` and `else_` above are static, immediate values determined at compile-time.
Though if either or both of them are resultants of function calls, unnecessary evaluation(s) will happen at runtime!

So, allowing oneline if-then-else might have a practical "defensive" value in that it prevents someone like me from introducing such suboptimal escape hatch!

**Comment by ianp** [comment]
@ymtszw yup, you probably want your function to have this type signature instead:

```elm
its: Bool -> (() -> a) -> (() -> a) -> a
its c t e =
  if c then
    t ()
  else
    e ()
```

and then invoke it like

```elm
ite c (\_ -> t) (\_ -> e)
```

which is kind of a pain!

**Comment by andys8** [comment]
An example with `elm-ui` and a border on the bottom, if selected:

### Current formatting

```elm
    el
        [ paddingXY 15 30
        , Border.color styles.colors.blue
        , Border.widthEach
            { top = 0
            , left = 0
            , right = 0
            , bottom =
                if isSelected then
                    4

                else
                    0
            }
        ]
    <|
        text content
```

### Formatting I'd prefer

```elm
    el
        [ paddingXY 15 30
        , Border.color styles.colors.blue
        , Border.widthEach
            { top = 0
            , left = 0
            , right = 0
            , bottom = if isSelected then 4 else 0
            }
        ]
    <|
        text content
```

**Comment by holgerl** [comment]
It has been almost three years now. Can we get a conclusion on this issue?

**Comment by andys8** [comment]
My impression is that if somebody submits a pull request for this feature, it will most likely get merged.

* Richard wrote he is fine with it
* Evan is using single line if statements in elm/core
* Aaron said the feature is planned

**Comment by andys8** [comment]
Regarding the implementation:

Here is the formatting done.

https://github.com/avh4/elm-format/blob/abe730aa441794373729ca25ed5164e90a05d65c/src/ElmFormat/Render/Box.hs#L1393-L1424

Changing it to print in a single line should be easy. But I guess we want it to be context sensitive: If there are line breaks, they should stay, and if there are none, then it should be printed in single line. I think this information has to be collected when parsing and represented like it's done for other features (e.g. imports)

**Comment by andys8** [comment]
Using `elm-ui`:

```elm

**Comment by XamiKami** [comment]
any updates on this? its driving me crazy...

**Comment by rlefevre** [comment]
It seems there are enough real-world examples to justify testing an implementation, so I made [one](https://github.com/avh4/elm-format/pull/648) that only leads to single line expressions if there is no `else if` nor multi-line expressions in the condition, else body or else body.

It seems to work quite well. The only drawback I noticed for now is that the following expression:
```
if if a then True else False then "a" else "b"
```
which was previously formatted as:
```
    if                                        
        if a then    
            True    
            
        else    
            False    
    then    
        "a"    
    
    else    
        "b"  
```
stays formatted as:
```
if if a then True else False then "a" else "b"
```
which might be a little confusing. 

I'm not sure if nested if conditions should be handled differently or not, given their rarity (the elm-format test that uses one is the only example I ever saw).

**Comment by ymtszw** [comment]
> ```
> if if a then True else False then "a" else "b"
> ```
> 
> 
> which might be a little confusing.

Inserting parens might indeed looks better.

```elm
if (if a then True else False) then "a" else "b"
```

However, as you probably noticed this should usually be reduced to:

```elm
if a then "a" else "b"
```

I wonder if there are practical cases where "nested `if`s" are justified in Elm.
For example, negating a `Bool` value should better be written with `Basics.not`, instead of nesting `if`s.

```elm
-- BAD
if (if a then False else True) then "a" else "b"

-- GOOD
if not a then "a" else "b"

-- GOOD; with a function call
if not (resolvesToBool a) then "a" else "b"
```

IMHO "nested `if`s" cause less concerns in reality since they are usually weeded out in code reviews (or, possibly by linters such as elm-analyse.)

Also as I wrote this, I started to wonder should longer conditional expressions be parenthesized?

```elm
-- This:
if conditionalFunction (isActually quite complicated) andOrLong then "what should we do?" else "b"

-- Or this:
if (conditionalFunction (isActually quite complicated) andOrLong) then "what should we do?" else "b"
-- However I would prefer extracting such long conditional values to `let` bindings.
```

My overall impression is: **just leave them without parens.**

- If the conditional part is just a single token or a short enough expression, it is OK
- Even if it is longer, the syntax highlighting helps us good
- Nested `if`s are assumingly rare enough
- From implementation POV, drawing a line between "long" and "short" is somewhat subjective and cumbersome, if we are to parenthesize "long" expressions.
