### ISSUE TITLE
Inserts no newlines after destructured tuple definition

### ISSUE THREAD

**Issue by mgold** [avh4/elm-format#218]
Input:

``` elm
module SSCCE exposing (..)

{-| Module comment.
-}


( a, b ) = ( 1, 2 )

foo = 5
```

Expected output (excerpt):

``` elm
( a, b ) =
    ( 1, 2 )


foo =
    5
```

Actual output (excerpt):

``` elm
( a, b ) =
    ( 1, 2 )
foo =
    5
```

This could be a bug in the parser not expecting top-level definitions to have a `(` or similar. It works as expected for definitions in a `let`. I'm using `elm-format-0.17 0.4.0-alpha`.

**Comment by avh4** [comment]
Yes, there's logic here https://github.com/avh4/elm-format/blob/master/src/ElmFormat/Render/Box.hs#L332-L354 to group top-level nodes together.  I'd guess it's that logic that is at fault here.

Thanks for reporting this.

**Comment by avh4** [comment]
This appears to have been fixed sometime between 0.4.0 and 0.6.2

**Comment by avh4** [comment]
Added tests in 160d8332...af0845d7

**Comment by mgold** [comment]
Confirmed, thanks!
