### ISSUE TITLE
usage for --stdin

### ISSUE THREAD

**Issue by mukeshsoni** [avh4/elm-format#222]
How do i exactly use the `--stdin` option? I don't get any output when i try it on my terminal in OSX.

Also, can i just pass a string as an input and get the formatted output as a string?

**Comment by avh4** [comment]
you would use like this: `cat MyFile.elm | elm-format --stdin`

**Comment by mukeshsoni** [comment]
Thanks @avh4 ! Went ahead with `echo "code" | elm-format --stdin`
