### ISSUE TITLE
elm-format for elm-17 converts "module Todo exposing (..)" to "module Todo (..) where"

### ISSUE THREAD

**Issue by BigTom** [avh4/elm-format#223]
Running on Macbook pro

using elm-format-0.17-0.4.0-alpha-mac-x64.tgz download

Happy to provide more info as required.

**Comment by rtfeldman** [comment]
Are you sure you have the 0.17 one and not the 0.16 one? That's the intended behavior of the 0.16 one, and personally I've definitely downloaded the wrong one before... 😄

**Comment by BigTom** [comment]
I think they are the same:
-rw-r--r--@ 1 tom  staff  1242175 20 Aug 11:20 elm-format-0.16-0.4.0-alpha-mac-x64.tgz
-rw-r--r--@ 1 tom  staff  1242171 20 Aug 11:20 elm-format-0.17-0.4.0-alpha-mac-x64.tgz

**Comment by BigTom** [comment]
Just noticed they are not quite the same size.  They do both exhibit the same behaviour though.

**Comment by avh4** [comment]
Please run `elm-format` and verify that it prints

```
elm-format-0.17 0.4.0-alpha
```

as the first line of output

**Comment by BigTom** [comment]
Yes it does, but I have downloaded a newer version.  It is now fixed.

elm-format-0.17 0.4.0-alpha
