### ISSUE TITLE
Proposal: 2 space indentation

### ISSUE THREAD

**Issue by jehoshua02** [avh4/elm-format#226]
I sincerely object to the 4 space indentation currently implemented in elm-format.

I hope I'm not shooting myself in the foot, but I propose 2 space indentation. Here's why:

+ __Adoption__. Judging by the many open source projects out there, many developers already have their editors configured for 2 space indentation for their css, javascript, and html. But whatever. I have other, more pragmatic reasons. Looks like the [examples](http://elm-lang.org/examples), and even http://guide.elm-lang.org/ favor 2 space indentation. The core lib docs however seem to favor 4 space indentation, in those few cases where indented code is displayed. The source code for elm core is all over the place, some 2, some 4, even in the same file.
+ __Display Consistency__. I like my code to look the same no matter where it is displayed. Spaces are displayed consistently everywhere.
+ __Less Horizontal Scrolling__. Especially when running split screen, with test on one side and source on the other.
+ __Less is More__. Less indentation, means you have a few more characters, especially when indented several levels, before you run into the line-length limit and have to split that line of code in an awkward way.
+ __Easier to Read__. After having been on both sides of the religious battle, I find 2 spaces much easier to read than 4 spaces/tabs. Maybe it's because my eyes have less distance to travel or some other reason I'm unaware of.

Example

__4 space__

```
tests : Test
tests =
    describe "Gigasecond"
        [ describe "add"
            [ test "2011-04-25" <|
                \() ->
                    Expect.equal (date "2043-01-01T01:46:40") (Gigasecond.add (date "2011-04-25"))
            , test "1977-06-13" <|
                \() ->
                    Expect.equal (date "2009-02-19T01:46:40") (Gigasecond.add (date "1977-06-13"))
            , test "1959-07-19" <|
                \() ->
                    Expect.equal (date "1991-03-27T01:46:40") (Gigasecond.add (date "1959-07-19"))
            , test "full time specified" <|
                \() ->
                    Expect.equal (date "2046-10-02T23:46:40") (Gigasecond.add (date "2015-01-24T22:00:00"))
            , test "full time with day roll-over" <|
                \() ->
                    Expect.equal (date "2046-10-03T01:46:39") (Gigasecond.add (date "2015-01-24T23:59:59"))
            ]
        ]
```

__2 space__

```
tests : Test
tests =
  describe "Gigasecond"
    [ describe "add"
      [ test "2011-04-25" <|
        \() ->
          Expect.equal (date "2043-01-01T01:46:40") (Gigasecond.add (date "2011-04-25"))
      , test "1977-06-13" <|
        \() ->
          Expect.equal (date "2009-02-19T01:46:40") (Gigasecond.add (date "1977-06-13"))
      , test "1959-07-19" <|
        \() ->
          Expect.equal (date "1991-03-27T01:46:40") (Gigasecond.add (date "1959-07-19"))
      , test "full time specified" <|
        \() ->
          Expect.equal (date "2046-10-02T23:46:40") (Gigasecond.add (date "2015-01-24T22:00:00"))
      , test "full time with day roll-over" <|
        \() ->
          Expect.equal (date "2046-10-03T01:46:39") (Gigasecond.add (date "2015-01-24T23:59:59"))
      ]
    ]
```

Whatever the outcome, I will accept whatever decision is made. If anyone has more objective evidence I'd like to see it.

**Comment by Janiczek** [comment]
@jehoshua02 `elm-format` supports 4 spaces only. Here's some relevant (and quite extensive) discussion: https://github.com/avh4/elm-format/issues/158

**Comment by jehoshua02** [comment]
@Janiczek I wouldn't call it extensive by any means, but a decision has been made and I can respect that.

**Comment by zwhitchcox** [comment]
So, can we configure it to use 2 spaces? I'm not going to use it if it's four spaces

**Comment by Janiczek** [comment]
@zwhitchcox There's no user configuration option for that. You could compile `elm-format` from source with the [relevant constant changed](https://github.com/avh4/elm-format/blob/master/src/Box.hs#L250) and use that if that's worthwhile to you.

**Comment by zwhitchcox** [comment]
Thank you...I ended up just having a regex replace the four spaces with 2 after a successful format. Unfortunately, I just do not have the screen real estate for four spaces

**Comment by AntouanK** [comment]
So a plug-in that all it does is style the format of the code, does not have an option to change the most non-standard thing in code formatting?
Why?

**Comment by Janiczek** [comment]
One less thing to worry about.

**Comment by scarfacedeb** [comment]
I still don't understand how come 4 spaces has been chosen as a default, despite the fact that a lot of standard libraries use 2 spaces. (e.g. elm-lang/http)

**Comment by specious** [comment]
@zwhitchcox:

> "Unfortunately, I just do not have the screen real estate for four spaces"

👍
