### ISSUE TITLE
Spacing in arithmetic enumerations

### ISSUE THREAD

**Issue by jvoigtlaender** [avh4/elm-format#229]
I propose to always format `[exp1..exp2]` as `[exp1 .. exp2]`.

If both expressions are just plain integer literals it does not seem to matter much, since both `[1..5]` and `[1 .. 5]` look fine. But as soon as one puts more complicated expressions there, things look weird with how `elm-format` handles this currently. For example, I'd like to write either:
* `[i+1..n]` or
* `[i + 1 .. n]`

but `elm-format` reformats both into
* `[i + 1..n]`

which gives the wrong impression (when reading the code) that `1..n` belong together and `i` is somehow "added" to that enumeration. That is, it reads as if what we have there is conceptually `[i+(1..n)]` instead of `[(i+1)..n]`.

Same with stuff like `[2..n - 2]` and also more complex expressions (maybe not even arithmetic expressions) in place of one of the two borders of the enumeration.

**Comment by avh4** [comment]
Good catch!

I think the `[i + 1 .. n]` is more consistent with the rest of the current format rules.

However, what would you think about having a style rule to add parens in ranges with expressions?  So for example, `[i+1..n]` would format as `[(i + 1)..n]`

**Comment by jvoigtlaender** [comment]
I'd be happy with this as well.

**Comment by jvoigtlaender** [comment]
With the `[exp1..exp2]` syntax completely disappearing, this becomes a non-issue.
