### ISSUE TITLE
Remove workaround for escaped non-breaking space

### ISSUE THREAD

**Issue by rtfeldman** [avh4/elm-format#231]
If I write this:

```
nonBreakingSpace =
    "\x00A0"
```

elm-format converts it to this:

```
nonBreakingSpace =
    " "
```

If someone ever goes through and changes this value to the wrong thing, I cannot tell from visual inspection...so I'll probably never know until a surprising bug happens.

I think it'd be better if we didn't do this.

**Comment by avh4** [comment]
`\xA0` is a special case which currently breaks elm-compiler on Windows: https://github.com/avh4/elm-format/issues/132

Your requested behavior is what is intended, but we can't implement that until the elm-compiler bug is fixed.  https://github.com/elm-lang/elm-compiler/issues/1279

**Comment by avh4** [comment]
(dev note) See https://github.com/avh4/elm-format/commit/816b5603bd2799104b6cc220e3cefe9e6a3478e7
