### ISSUE TITLE
Arrows move depending on developer

### ISSUE THREAD

**Issue by note89** [avh4/elm-format#232]
Any idea why one of our developers reformats the whole file in this way everytime he saves ? 
![image](https://cloud.githubusercontent.com/assets/6696963/18354454/eea9deb8-75e5-11e6-833d-32efd7b80e19.png)

**Comment by avh4** [comment]
Yes! One of your developers is using elm-format-0.4.0-alpha and the other
is using an older version.

**Comment by note89** [comment]
Tnx alot, that was fast ! Well pretty noob by me. forgot that atom did not download `elm-format`.

**Comment by avh4** [comment]
(I think this is solved.)
