### ISSUE TITLE
How to add to Path?

### ISSUE THREAD

**Issue by kittykatattack** [avh4/elm-format#238]
Hi Everyone,

I'm trying to add `elm-format` to my Path but haven't been able to figure our how yet.
My Path looks like this:

`/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`

I've dropped the `elm-format` file into my `/usr/bin` folder - is that all I need to do, or do I have to modify my `.bash_profile` as well?

**Comment by Janiczek** [comment]
Adding it into any of these folders should be enough. The other way around is having it in some custom folder and adding that folder to the beginning of the PATH list (in .bash_profile or .bashrc), then restarting the terminal to load that change.

**Comment by kittykatattack** [comment]
Thanks, it looks like it's working 👍
