### ISSUE TITLE
Formatting comments on the same line as the code

### ISSUE THREAD

**Issue by newlandsvalley** [avh4/elm-format#246]
Before:

``` elm
type MyType =
     Foo  -- this is a Foo
  |  Bar  -- this is a Bar
  |  Baz  -- this is a Baz
```

After:

``` elm
type MyType
    = Foo
      -- this is a Foo
    | Bar
      -- this is a Bar
    | Baz



-- this is a Baz

```

This is surely not right.  But what is the generally accepted way to comment ADTs like this in Elm?  Are you meant to put the comment after the code to which it applies?

**Comment by avh4** [comment]
You are correct.  What you are asking about is one of the last remaining features that needs to be finished before the 1.0 release.  The issue is being tracked here: https://github.com/avh4/elm-format/issues/162

**Comment by avh4** [comment]
The original example now formats as

```elm
type MyType
    = Foo -- this is a Foo
    | Bar -- this is a Bar
    | Baz -- this is a Baz
```
