### ISSUE TITLE
Elm 0.18: tuple functions have been moved to Tuple.func

### ISSUE THREAD

**Issue by eeue56** [avh4/elm-format#259]
`fst (1, 2)`
becomes

``` elm
import Tuple
Tuple.first (1, 2)
```

And `snd` -> `Tuple.second`

**Comment by avh4** [comment]
Won't Tuple be a default import?

**Comment by avh4** [comment]
> Won't Tuple be a default import?

Apparently not https://github.com/elm-lang/elm-compiler/blob/master/src/Elm/Compiler/Imports.hs

**Comment by avh4** [comment]
Next beta of Elm will import `Tuple` by default, so this will simply transform `fst` or `Basics.fst` -> `Tuple.first`; and `snd` or `Basics.snd` -> `Tuple.second`

**Comment by avh4** [comment]
Fixed in 03a8946...6a39ec0
