### ISSUE TITLE
0.18 release build

### ISSUE THREAD

**Issue by avh4** [avh4/elm-format#265]
- [x] remove incomplete `--json` from the branch
 - [x] build Mac
 - [x] build Win
 - [x] build Linux

**Comment by bdukes** [comment]
@avh4 It looks like the Windows 0.18 release is actually an old 0.16 release (it says "elm-format-0.16 0.4.0-alpha" and doesn't know about the `--upgrade` option)

**Comment by bdukes** [comment]
Actually, I'm seeing the same results for all of the windows 0.5.0 releases

**Comment by avh4** [comment]
Hmm.. okay, I will rebuild it now

**Comment by avh4** [comment]
@bdukes should be fixed now.  Thanks for reporting!

**Comment by bdukes** [comment]
Yes, it's working now, thanks!
