### ISSUE TITLE
Upgrade uses of `:=` (from Json.Decode)

### ISSUE THREAD

**Issue by avh4** [avh4/elm-format#268]
> For me, the biggest remaining item that makes the 0.18 upgrade tedious is dealing with the removal of (:=). The problem is that it (1) occurs frequently and (2) cannot be fixed with a simple find-and-replace because the right-hand-side arg to the binary operator may need additional parenthesis to achieve the right precedence after switching to field

**Comment by avh4** [comment]
I'm debating whether or not to do this.. `a := b` would become `Json.Decode.field a b`.  But this might lead to other confusion, since other things in Json.Decode have to change, but won't be upgraded by elm-format.

**Comment by avh4** [comment]
0.5.0 is released, and I'm going to leave this alone.

**Comment by klazuka** [comment]
👍
The 0.18 upgrade process is a big leap forward from previous releases, so it's okay to not handle everything. Plus it gives us room for improvement when the next major release launches.
