### ISSUE TITLE
List.range conversion for [Namespace.exp1..Namespace.exp2]

### ISSUE THREAD

**Issue by manuscrypt** [avh4/elm-format#274]
Not sure, if this should be on elm-format after the last one I posted.
Here is the piece of code that didn't convert correctly:

```
 let
        all =
            List.map (String.fromChar << Char.fromCode)
                [Ascii.fromCode..Ascii.toCode]
```
where

```
fromCode : Int
fromCode =
    32


toCode : Int
toCode =
    126
```
Thanks again for a great tool!

**Comment by avh4** [comment]
It looks like you aren't running `elm-format` with the `--upgrade` flag?  I am unable to reproduce your issue.  It works correctly for me with elm-format-0.5.1 and elm-format-0.5.0.

**Comment by manuscrypt** [comment]
I was only running elm-upgrade, that's why I am so confused. Are you telling me, that the correct way to upgrade an elm-project is to first run elm-upgrade, then run elm-format --upgrade? If so, sorry for the confusion.

**Comment by avh4** [comment]
Ah, in that case, can you verify that you're using elm-upgrade version 0.18.0 or higher?  (Not version 0.18.0-alpha)

**Comment by manuscrypt** [comment]
elm-upgrade --version
INFO: Found elm at /usr/local/bin/elm
INFO: Found elm-format at /usr/local/bin/elm-format
INFO: Found Elm Platform 0.18.0
INFO: Found 0.5.0-alpha
ERROR: You must run the upgrade from a folder containing elm-package.json

**Comment by manuscrypt** [comment]
sorry:
sudo npm -g list elm-upgrade
/usr/local/lib
└── elm-upgrade@0.18.4

**Comment by avh4** [comment]
Is the elm file in question underneath a folder that is listed in the `source-directories` in the `elm-package.json` in the folder where you're running `elm-upgrade` from?

**Comment by manuscrypt** [comment]
No, it's in examples/,  which is not listed there. Just ignore me, that makes a lot of sense. :blush:

**Comment by avh4** [comment]
I wonder if elm-upgrade should just elm-format the entire folder ... also related is https://github.com/avh4/elm-upgrade/issues/7

**Comment by manuscrypt** [comment]
:thumbs_up:
