### ISSUE TITLE
Don't search node_modules if `.` is listed as a source dependency.

### ISSUE THREAD

**Issue by jackfranklin** [avh4/elm-format#278]
Taken from https://github.com/avh4/elm-upgrade/issues/17#issuecomment-261398410.

**Comment by eeue56** [comment]
node_modules should not be in your Elm source-directories.

**Comment by jackfranklin** [comment]
It wasn't. I had a node_module installed that had some `example/Foo.elm` that `elm-upgrade` picked up. Maybe it's not limiting its search correctly?

**Comment by eeue56** [comment]
Can you explain what your directory tree looks like? Can you explain what you mean by source dependency?

**Comment by jackfranklin** [comment]
I have Elm files in the root directory, and my `elm-package.json` listed the `src` directories as just `.`.

I have a node dependency in `node_modules/gulp-elm` that includes a dummy Elm file at: `node_modules/gulp-elm/examples/Demo.elm`.

When I ran `elm-upgrade` (which in turn ran `elm-format`) it tried to format `node_modules/gulp-elm/examples/Demo.elm`, which I wouldn't expect.

**Comment by rundis** [comment]
Don't use `.` (dot aka everything) as a source directory in elm-package.json ?

**Comment by jackfranklin** [comment]
Sure, this is an older project and I have moved onto `src` by default.

I do think a lot of people use `.` though and I would argue that ignoring `node_modules` by default is sensible (or perhaps ignoring anything that's ignored by Git?).

That said it might not be as big of a deal, in which case feel free to close this.

**Comment by eeue56** [comment]
Right, yeah. `node_modules` should not be in your source-directories, really. If it's in the same dir as elm-package.json, and you list `.` as a directory, then it's going to look in there. And it should look in there.

I think adding an `--exclude` flag mgiht be helpful.

**Comment by eeue56** [comment]
Ignoring things that are ignored in .gitignore is generally not a good way to do things. It introduces magic into the system, and reduces the amount you can rely on it.

**Comment by jackfranklin** [comment]
Fair enough, I can buy that arguments. I do think having `node_modules` as a default excluded/blacklisted folder would be sensible but I appreciate not wanting magic.

**Comment by avh4** [comment]
I think the original issue here was fine. It's common to have . as a source directory, and it's common to have ./node_modules.  It's also common to have ./tests/node_modules when . is a source directory.

I'm leaving this issue as described.

Please open a new discussion issue if you want to debate alternative solutions.

**Comment by avh4** [comment]
Fixed in 021b55a0
