### ISSUE TITLE
Handle glshader expressions

### ISSUE THREAD

**Issue by avh4** [avh4/elm-format#28]
`AST.Expression.GLShader`. 

```elm
vertexShader : Shader { position:Vec3, coord:Vec3 } { u | view:Mat4 } { vcoord:Vec2 }
vertexShader = [glsl|

attribute vec3 position;
attribute vec3 coord;
uniform   mat4 view;
varying   vec2 vcoord;

void main () {
  gl_Position = view * vec4(position, 1.0);
  vcoord = coord.xy;
}

|]
```

**Comment by Fresheyeball** [comment]
:+1:  elm-format told me to report this

```elm
fragmentShader : Shader {} u { vcolor : Vec3 }
fragmentShader =
    <TODO: glshader -- please report this at https://github.com/avh4/elm-format/issues >
```

**Comment by avh4** [comment]
Fixed in 04544da.

**Comment by Fresheyeball** [comment]
That was fast :100:

**Comment by avh4** [comment]
:+1: the last time I looked at this was when I was just starting out in haskell.  I figured I'd wait to hear that people were actually using this before figuring out how to implement it.  Turns out it was a lot easier than I had imagined!

**Comment by nphollon** [comment]
And I was just about to report it too. What perfect timing :-D
