### ISSUE TITLE
Updating nested records. 

### ISSUE THREAD

**Issue by colbydehart** [avh4/elm-format#282]
I was working through DailyDrip's elm tutorials and was working on the todo excercise when I noticed this bug. The answer for the excercise was an update case to add a new todo and clear the input todo's title. This is what he had.

```
update : Msg -> Model -> Model
update msg model =
    case msg of
        -- ...
        UpdateField str ->
          {model | todo = { model.todo | title = str } }
        -- ...
```

When I try to use this answer, elm-format complains:

```
"Main.elm" 514L, 10130C writtenelm-format: -- SYNTAX PROBLEM - /var/folders/cc/dmzywn5x6_b3npyt9y1bcjsr0000gn/T/nvimsx1ruj/82.elm

I ran into something unexpected when parsing your code!

62│                 , todo = { model.todo | title = "" }
                                    ^
I am looking for one of the following things:

    "|"
    =
    more letters in this name
    whitespace


Processing file /var/folders/cc/dmzywn5x6_b3npyt9y1bcjsr0000gn/T/nvimsx1ruj/82.elm
ERRORS
```

Not really sure what is going on here. Tried every different form of indentation and nothing seemed to work. Does elm-format not support updating nested records?

**Comment by stil4m** [comment]
I believe this is not valid Elm code, so this is not an issue for `elm-format`. Instead you should use a `let...in` to achieve this.

```
let 
    oldTodo = model.todo
in 
   {model | todo = { oldTodo | title = str } }
```

**Comment by colbydehart** [comment]
Ah, you are right. sorry you answered before I could remove my dumb question! The tutorial must be a bit outdated. Sorry for wasting time. Love this tool, coming from JS a standard style guide/formatter is extremely helpful, especially with a code layout that is unfamiliar to me. Thanks!
