### ISSUE TITLE
Comments in pipeline

### ISSUE THREAD

**Issue by ehamberg** [avh4/elm-format#287]
I have some code with pipelines that do date manipulation. In some of the more subtle cases there are comments explaining what each step does. For some reason, `elm-format` will re-format the lines following comments to have the `|>` operator on a line of its own and then indent what comes after, turning 

```elm
                mondayOfPrevWeek =
                    date
                        -- find Monday of this week …
                        |> add Day (1 - currentWeekDay)
                        -- … then subtract a week
                        |> add Week -1
                        |> isoDateString
```

into

```elm
                mondayOfPrevWeek =
                    date
                        -- find Monday of this week …
                        |>
                            add Day (1 - currentWeekDay)
                        -- … then subtract a week
                        |>
                            add Week -1
                        |> isoDateString
```

I guess this isn't expected behaviour since it won't do it without the comments being there.

**Comment by xarvh-at-stax** [comment]
This.
I'm struggling to properly comment my code.

**Comment by ehamberg** [comment]
This seems to be working in elm-format-0.18. 👍
