### ISSUE TITLE
Windows 32 bit

### ISSUE THREAD

**Issue by kbsymanz** [avh4/elm-format#293]
I am teaching a beginning Elm class in a small high school using a computer lab with 32 bit desktop computers running Windows 7. It would be great if there was a release of elm-format for this platform. So many of my students problems ultimately come down to formatting issues. What are the chances of getting this release?

Thanks

**Comment by avh4** [comment]
I don't understand much about building on Windows... I currently have a special machine set up to build the Windows binaries, and would be happy to build 32-bit if I can figure out how to.

**Comment by kbsymanz** [comment]
(Sorry about the late reply, I was travelling from Asia to the US.)

I hear you, I don't understand about building Windows much either since I have been using Linux for a long time. I will research a bit to see what I can find out about that and about the 32/64 bit question you raised.

**Comment by kbsymanz** [comment]
I successfully compiled a Windows 32 bit version of the program within a Windows 64 bit environment using a 32 bit version of Haskell Stack. I am having a friend test it within a Windows 32 bit environment and will let you know if it works.

Also, the 32 bit program did work fine within a 64 bit Windows environment. The bit of checking that I did indicates that backward compatibility like this is par for the course.

**Comment by kbsymanz** [comment]
Ok, just got confirmation back that the Windows 32 bit version that I compiled as mentioned above is working fine on 32 bit machines.

**Comment by avh4** [comment]
Can someone verify whether this binary works on 32-bit windows?  [elm-format-0.18.exe.zip](https://github.com/avh4/elm-format/files/854136/elm-format-0.18.exe.zip)

**Comment by avh4** [comment]
32-bit snapshots are now built with appveyor, and publishing instructions are updated to build 32-bit binaries for the 0.6.0-alpha release.
