### ISSUE TITLE
automate build of Windows binaries

### ISSUE THREAD

**Issue by avh4** [avh4/elm-format#295]
What is the best way to do this?

  - Windows docker containers?  http://blog.contino.io/getting-started-with-windows-containers
  - Cross-compilation with ghc?

**Comment by domenkozar** [comment]
appveyor

**Comment by avh4** [comment]
Appveyor build is working now (as of 7e94034a): https://ci.appveyor.com/project/avh4/elm-format

**Comment by rtfeldman** [comment]
Whoooooooooooooooa

**Comment by avh4** [comment]
Fixed in https://github.com/avh4/elm-format/pull/694 and https://github.com/avh4/elm-format/pull/705

(Though it would still be preferable to figure out a way to do cross-compilation inside of a linux docker container, but that'll be for a future issue :) )
