### ISSUE TITLE
Allow aligning imports, records and others

### ISSUE THREAD

**Issue by G4BB3R** [avh4/elm-format#297]
I am loving elm-format, but I am sad that it removes the alignment:
```
import AAAAA exposing (..)
import B     exposing (..)
import CC    exposing (..)
```
to
```
import AAAAA exposing (..)
import B exposing (..)
import CC exposing (..)
```
and
```
type alias Model =
    { id               : Int
    , name             : String
    , longFieldNameIdk : String
    , time             : Time
    , profit           : Int
    }
```
to
```
type alias Model =
    { id : Int
    , name : String
    , longFieldNameIdk : String
    , time : Time
    , profit : Int
    }
```

What about a settings to allow alignment? It helps a lot with readability

**Comment by avh4** [comment]
Hi, this is not a feature that elm-format will have in the foreseeable future.  Aligning things like that means that if the length of the longest field changes, then all the lines in the record must change, which leads to messy diffs.  This is a case where the goals of readability and maintainability are at odds, and in this case, elm-format chooses to prefer maintainability.
