### ISSUE TITLE
PGP signatures: No public key

### ISSUE THREAD

**Issue by skarger** [avh4/elm-format#298]
The README says:
> If you need PGP signatures, see the releases page.

It's possible I'm doing it wrong, but when I try to verify the signature I can't seem to get your public key.

### To reproduce the problem:
1. From the releases page I downloaded `elm-format-0.18-0.5.2-alpha-mac-x64.tgz.asc` and `elm-format-0.18-0.5.2-alpha-mac-x64.tgz.asc`. 

2. Obtained the key ID from the signature:
```
$ gpg --version
gpg (GnuPG) 2.0.30
libgcrypt 1.7.3

$ gpg -vv elm-format-0.18-0.5.2-alpha-mac-x64.tgz.asc
gpg: armor: BEGIN PGP SIGNATURE
:signature packet: algo 1, keyid 11357FB6FDD7BEC0
	version 4, created 1479276346, md5len 0, sigclass 0x00
	digest algo 8, begin of digest 0c 18
	hashed subpkt 2 len 4 (sig created 2016-11-16)
	hashed subpkt 16 len 8 (issuer key ID 11357FB6FDD7BEC0)
	data: [4096 bits]
gpg: assuming signed data in 'elm-format-0.18-0.5.2-alpha-mac-x64.tgz'
gpg: Signature made Wed Nov 16 01:05:46 2016 EST using RSA key ID FDD7BEC0
gpg: Can't check signature: No public key
```

3. Tried to grab the public key from a various key servers:
```
$ gpg --keyserver pool.sks-keyservers.net --recv-keys 11357FB6FDD7BEC0
gpg: requesting key FDD7BEC0 from hkp server pool.sks-keyservers.net
gpgkeys: key 11357FB6FDD7BEC0 not found on keyserver
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: Not found
gpg: keyserver communications error: Bad public key
gpg: keyserver receive failed: Bad public key

$ gpg --keyserver pgp.mit.edu --recv-keys 11357FB6FDD7BEC0
gpg: requesting key FDD7BEC0 from hkp server pgp.mit.edu
gpgkeys: key 11357FB6FDD7BEC0 not found on keyserver
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: Not found
gpg: keyserver communications error: Bad public key
gpg: keyserver receive failed: Bad public key

$ gpg --keyserver  keys.gnupg.net --recv-keys 11357FB6FDD7BEC0
gpg: requesting key FDD7BEC0 from hkp server keys.gnupg.net
gpgkeys: key 11357FB6FDD7BEC0 not found on keyserver
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: Not found
gpg: keyserver communications error: Bad public key
gpg: keyserver receive failed: Bad public key
```

Are you intending for people to do it differently?

**Comment by avh4** [comment]
Hello,  the keys are available here:  https://keybase.io/avh4

elm-format is the only thing I use PGP for, so if you have a suggestion of how to improve things, let me know.

**Comment by skarger** [comment]
@avh4 thanks for the link, I used the process below successfully. The only suggestion I have is to include your keybase link on the README or releases page. I like being able to sanity check downloaded binaries, but I don't know enough about PGP/crypto to advise best practices.

Thanks for elm-format, it's been very helpful.

```
$ curl https://keybase.io/avh4/pgp_keys.asc > avh4.asc

$ gpg --import avh4.asc
gpg: key 3F6CCA93: public key "keybase.io/avh4 <avh4@keybase.io>" imported
gpg: key FDD7BEC0: public key "Aaron VonderHaar <gruen0aermel@gmail.com>" imported
gpg: Total number processed: 2
gpg:               imported: 2  (RSA: 2)

$ gpg -vv elm-format-0.18-0.5.2-alpha-mac-x64.tgz.asc
gpg: armor: BEGIN PGP SIGNATURE
:signature packet: algo 1, keyid 11357FB6FDD7BEC0
	version 4, created 1479276346, md5len 0, sigclass 0x00
	digest algo 8, begin of digest 0c 18
	hashed subpkt 2 len 4 (sig created 2016-11-16)
	hashed subpkt 16 len 8 (issuer key ID 11357FB6FDD7BEC0)
	data: [4096 bits]
gpg: assuming signed data in 'elm-format-0.18-0.5.2-alpha-mac-x64.tgz'
gpg: Signature made Wed Nov 16 01:05:46 2016 EST using RSA key ID FDD7BEC0
gpg: using PGP trust model
gpg: Good signature from "Aaron VonderHaar <gruen0aermel@gmail.com>" [unknown]
```

**Comment by avh4** [comment]
Added details to the README in c57fd8a3...461e462a

**Comment by emilianobovetti** [comment]
Hey @avh4 I see the details on how to import the key for verification have been updated on https://github.com/avh4/elm-format/commit/e91bc4e3385f83006856ec843798826ad645c50d, and again in https://github.com/avh4/elm-format/commit/e9260936922d0d8881843d477c9000b4e0c9fd0d where any reference to PGP/verification has been removed.

I'm generally a bit more ~careless~ brave when downloading binaries and I don't verify signatures, but it seems like nobody feels safe adopting the [elm-format-bin](https://aur.archlinux.org/packages/elm-format-bin) AUR package until we can solve this issue (see also the related https://github.com/avh4/elm-format/pull/341).

So the problem is that the current key cannot be found even on https://keybase.io/avh4
```
$ gpg --verify elm-format-0.8.8-linux-x64.tgz.asc
gpg: assuming signed data in 'elm-format-0.8.8-linux-x64.tgz'
gpg: Signature made Thu Jun 19 04:07:42 2025 CEST
gpg:                using RSA key 0B8C5B2A641C542ECF5D4077C2B2C4C124E96476
gpg: Can't check signature: No public key
```

I'd be fine in adopting the package and removing the signature verification, but I'm looking for an advise here since the `.tgz.asc` files are still published in each release it does seem like we are supposed to check the signature downstream.
