### ISSUE TITLE
Handle comments (block comments and line comments)

### ISSUE THREAD

**Issue by rtfeldman** [avh4/elm-format#3]
Block comments and line comments anywhere in the file need to be handled reasonably.

See https://github.com/rtfeldman/dreamwriter/compare/elm-format?expand=1#diff-cd8e6cfa12c24161b452f61a98434468R52 - that block comment moved considerably from where it started out!

### Top-level constructs
- [x] port declarations
- [x] infix declarations
- [x] type declarations
- [x] type alias declarations
- [x] definition (Expression.definition)
- [x] definition patterns
- [x] before module statement
- [x] module statement
- [x] within module export listings
- [x] top-level
- [x] around import statements
- [x] within import statements
- [x] within import listings
- [x] within union type listings
- [x] within open listings
- ~~within closed listings~~
- [x] type annotations

### Expressions
- [x] unit
- [x] symbolic operators
- [x] binary operator expressions
- [x] function application
- [x] parenthesized expressions
- [x] tuples
- [x] tuple constructor functions
- [x] list
- [x] empty list
- [x] literal records
- [x] record updates
- [x] if statement conditions
- [x] if statement bodies
- [x] lambda arguments
- [x] lambda bodies
- [x] case subjects
- [x] case patterns
- [x] case bodies
- [x] let expressions
- [x] infix definition patterns

### Types
- [x] unit types
- [x] tuple types
- [x] record types
- [x] record extension types
- [x] empty record types
- [x] type constructor arguments
- [x] function types
- [x] parenthesized types

### Patterns
- [x] constructor patterns
- [x] unit pattern
- [x] parenthesized patterns
- [x] tuple patterns
- [x] list patterns
- [x] cons patterns (`first::rest`)
- [x] empty list pattern
- [x] record patterns
- [x] pattern aliases

**Comment by avh4** [comment]
@rtfeldman Comments in a great many places are now handled properly.  Comments will no longer move.  Some will still be dropped, but I have a clear list of where all those places are and will be addressing them all (though some are places very unlikely to actually have comments: did you know this was a valid way to create a tuple? `myTuple = ({-comment?!-},,) 1 2 3`

**Comment by rtfeldman** [comment]
:smile:

**Comment by rtfeldman** [comment]
@avh4 Not sure if it's one of the cases on your list (if not, I'm happy to open an issue), but here's one where they currently get dropped:

```elm
type alias Foo =
    {- Snoop Dogg is gonna drop this comment like it's hot -}
    something
```

**Comment by avh4** [comment]
Thanks! I added it to the list.  (Though the real TODO list is as comments in the code, and I think I have every case noted there)

**Comment by avh4** [comment]
Okay, types are finished as of 6a8c993!  Only 22 more places...

**Comment by avh4** [comment]
Okay, patterns are finished as of e6cf606!  Only 14 more places...

**Comment by avh4** [comment]
Expressions are finished as of 8751dcd!  Only boring top-level things remain :)

**Comment by avh4** [comment]
Phew!  Finished in 5b156cb.  :tada: :tada:  Advice to future language authors: write your parser to model comments from day 1.

**Comment by rundis** [comment]
Well done ! :clap:

**Comment by rtfeldman** [comment]
![trooperdance](https://cloud.githubusercontent.com/assets/1094080/12637741/a4088e26-c565-11e5-85f0-c74a90804256.gif)

**Comment by Janiczek** [comment]
That's awesome! Thank you! :)
