### ISSUE TITLE
Crashes on empty comment

### ISSUE THREAD

**Issue by brian-carroll** [avh4/elm-format#315]
Hi,
I find when I have an empty comment in a file, elm-format throws an exception.
```
module EmptyComment exposing (..)

{-
   
-}
stuff =
    "things"
```
`elm-format: Prelude.minimum: empty list`

I guess an empty comment is a bit of an edge case but my code editor plugin was set up to format on save and mis-reported it as a problem with elm-format not being installed. Took me a while to track down as I didn't suspect the empty comment would cause a problem.
(I've also filed an [issue](https://github.com/abadi199/code-elm-format/issues/) with the maintainer of the plugin.)
Definitely a low priority one.
Fantastic library, thanks for creating it! :)

**Comment by avh4** [comment]
Fixed in f7dc5499
