### ISSUE TITLE
Comment containing only 1 empty line cannot be formatted

### ISSUE THREAD

**Issue by kirchner** [avh4/elm-format#321]
When running elm-format-0.18 (version 0.5.2-alpha) on the file containing

```
module Main exposing (..)

{-

-}

main = ()
```

I get the error:

```
elm-format-0.18: Prelude.minimum: empty list
```

If the comment is changed to

```
{-
-}
```

elm-format is successfull and produces

```
{-  -}
```

This can also be reproduced [here](https://ellie-app.com/DTWs8RSsMFa1/0).

**Comment by avh4** [comment]
Fixed in https://github.com/avh4/elm-format/issues/315 🎉
