### ISSUE TITLE
Comments in pipe chains force extra newlines

### ISSUE THREAD

**Issue by drathier** [avh4/elm-format#322]
Adding a comment in the middle of a few lines of piped functions forces a line break after the first pipe after the comment:

```
...
|> f a
|> f b
-- comment
|> 
  f c
|> f d
|> f e
...                 
```

I would like it to become

```
...
|> f a
|> f b
-- comment
|> f c
|> f d
|> f e
...                 
```

**Comment by avh4** [comment]
Fixed in https://github.com/avh4/elm-format/issues/310 🎉
