### ISSUE TITLE
Comments in records disrupt formatting of previous line

### ISSUE THREAD

**Issue by mordrax** [avh4/elm-format#328]
Not sure if related/fixed by: https://github.com/avh4/elm-format/issues/327 but I'm finding that comments inside a record declaration makes the type of the previous line start a newline.

Here's a SSCCE: https://ellie-app.com/HNbCyHT3sPa1/0

The motivation for commenting in records is because I'm trying to make a polymorphic type alias which can be grouped together but also typed separately: https://github.com/mordrax/cotwelm/pull/16/files#diff-342931ff364bca9382f8ed80eafde493R77

So now, I'd like to document where the fields comes from but adding documentation causes elm-format to be confused.

Ideally, the `--` comment would behave in much the same way as outside of a record, 2 spaces before/after the next line.

**Comment by mordrax** [comment]
Or even how the union type comments are setup now would be fine:
```
type ArmourType
    = RustyArmour
    | LeatherArmour
    ....
    | ElvenChainMail
      -- monster armour
    | SoftHide
    | Bones
```

**Comment by avh4** [comment]
This was implemented in https://github.com/avh4/elm-format/issues/257.  #327 is a regression bug that happened when implementing it :)

**Comment by mordrax** [comment]
ahhh, 👍  awesome! fwiw, I did scan the open issues list for reports... now I will search the closed issues list too.
Regression bugs in Elm... that's unusual.
