### ISSUE TITLE
npm installer should work on Windows

### ISSUE THREAD

**Issue by avh4** [avh4/elm-format#334]
Does this currently work (for 0.6.0-alpha)?  I haven't verified it yet, but I think it probably doesn't work, since `binstall` appears to only support `.tgz` files, and the Windows release is in a `.zip` file.

The fix is probably to make `binstall` support zip files.

**Comment by stil4m** [comment]
I've tested this and it does not work yet.

I've added a created a simple [repo](https://github.com/stil4m/elm-format-npm-windows) with an appveyor configuration that will just install elm-format locally. 
The [build](https://ci.appveyor.com/project/stil4m/elm-format-npm-windows) shows that this currently does not succeed.

**Comment by avh4** [comment]
Fixed in f00d61eb...cd39d3e1

**Comment by avh4** [comment]
Nevermind, it's not fixed yet.

**Comment by avh4** [comment]
I've updated it to extract the zip file, but now the exe is not getting put on the path correctly because package.json says the bin is `elm-format`, not `elm-format.exe`.  It looks like we need to set up the binwrappers thing used by elm-platform :(  https://github.com/elm-lang/elm-platform/blob/master/installers/npm/binwrap.js

**Comment by avh4** [comment]
I believe this is finally fixed in 270e86cb...eb2a091b

`npm install -g elm-format` should now work on Windows (and should be version `0.6.0-alpha.6`)

**Comment by Rolograaf** [comment]
The download for win gives me 0.6.0alpha but npm still 0.5.2alpa

**Comment by avh4** [comment]
Here's what I get running `npm install -g elm-format` on Windows.  It seems to install 0.6.0-alpha.  If you still have problems, can you give more details?

```
vagrant@vagrant-2012-r2 MINGW64 ~
$ elm-format
bash: elm-format: command not found

vagrant@vagrant-2012-r2 MINGW64 ~
$ npm install -g elm-format
C:\Users\vagrant\AppData\Roaming\npm\elm-format -> C:\Users\vagrant\AppData\Roaming\npm\node_modules\elm-format\bin\elm-format

> elm-format@0.6.0-alpha.6 install C:\Users\vagrant\AppData\Roaming\npm\node_modules\elm-format
> binwrap-install

C:\Users\vagrant\AppData\Roaming\npm
`-- elm-format@0.6.0-alpha.6
  `-- binwrap@0.1.4
    +-- request@2.81.0
    | +-- aws-sign2@0.6.0
    | +-- aws4@1.6.0
    | +-- caseless@0.12.0
    | +-- combined-stream@1.0.5
    | | `-- delayed-stream@1.0.0
    | +-- extend@3.0.0
    | +-- forever-agent@0.6.1
    | +-- form-data@2.1.2
    | | `-- asynckit@0.4.0
    | +-- har-validator@4.2.1
    | | +-- ajv@4.11.5
    | | | +-- co@4.6.0
    | | | `-- json-stable-stringify@1.0.1
    | | |   `-- jsonify@0.0.0
    | | `-- har-schema@1.0.5
    | +-- hawk@3.1.3
    | | +-- boom@2.10.1
    | | +-- cryptiles@2.0.5
    | | +-- hoek@2.16.3
    | | `-- sntp@1.0.9
    | +-- http-signature@1.1.1
    | | +-- assert-plus@0.2.0
    | | +-- jsprim@1.4.0
    | | | +-- assert-plus@1.0.0
    | | | +-- extsprintf@1.0.2
    | | | +-- json-schema@0.2.3
    | | | `-- verror@1.3.6
    | | `-- sshpk@1.11.0
    | |   +-- asn1@0.2.3
    | |   +-- assert-plus@1.0.0
    | |   +-- bcrypt-pbkdf@1.0.1
    | |   +-- dashdash@1.14.1
    | |   | `-- assert-plus@1.0.0
    | |   +-- ecc-jsbn@0.1.1
    | |   +-- getpass@0.1.6
    | |   | `-- assert-plus@1.0.0
    | |   +-- jodid25519@1.0.2
    | |   +-- jsbn@0.1.1
    | |   `-- tweetnacl@0.14.5
    | +-- is-typedarray@1.0.0
    | +-- isstream@0.1.2
    | +-- json-stringify-safe@5.0.1
    | +-- mime-types@2.1.15
    | | `-- mime-db@1.27.0
    | +-- oauth-sign@0.8.2
    | +-- performance-now@0.2.0
    | +-- qs@6.4.0
    | +-- safe-buffer@5.0.1
    | +-- stringstream@0.0.5
    | +-- tough-cookie@2.3.2
    | | `-- punycode@1.4.1
    | +-- tunnel-agent@0.6.0
    | `-- uuid@3.0.1
    +-- request-promise@4.2.0
    | +-- bluebird@3.5.0
    | +-- request-promise-core@1.1.1
    | | `-- lodash@4.17.4
    | `-- stealthy-require@1.0.0
    +-- tar@2.2.1
    | +-- block-stream@0.0.9
    | +-- fstream@1.0.11
    | | +-- graceful-fs@4.1.11
    | | +-- mkdirp@0.5.1
    | | | `-- minimist@0.0.8
    | | `-- rimraf@2.6.1
    | |   `-- glob@7.1.1
    | |     +-- fs.realpath@1.0.0
    | |     +-- inflight@1.0.6
    | |     | `-- wrappy@1.0.2
    | |     +-- minimatch@3.0.3
    | |     | `-- brace-expansion@1.1.6
    | |     |   +-- balanced-match@0.4.2
    | |     |   `-- concat-map@0.0.1
    | |     +-- once@1.4.0
    | |     `-- path-is-absolute@1.0.1
    | `-- inherits@2.0.3
    `-- unzip@0.1.11
      +-- binary@0.3.0
      | +-- buffers@0.1.1
      | `-- chainsaw@0.1.0
      |   `-- traverse@0.3.9
      +-- fstream@0.1.31
      | `-- graceful-fs@3.0.11
      |   `-- natives@1.1.0
      +-- match-stream@0.0.2
      +-- pullstream@0.4.1
      | +-- over@0.0.5
      | `-- slice-stream@1.0.0
      +-- readable-stream@1.0.34
      | +-- core-util-is@1.0.2
      | +-- isarray@0.0.1
      | `-- string_decoder@0.10.31
      `-- setimmediate@1.0.5


vagrant@vagrant-2012-r2 MINGW64 ~
$ which elm-format
/c/Users/vagrant/AppData/Roaming/npm/elm-format

vagrant@vagrant-2012-r2 MINGW64 ~
$ elm-format
elm-format-0.18 0.6.0-alpha

Usage: elm-format.exe [INPUT] [--output FILE] [--yes] [--validate] [--stdin]
                      [--elm-version VERSION] [--upgrade]
  Format Elm source files.

Available options:
  -h,--help                Show this help text
  --output FILE            Write output to FILE instead of overwriting the given
                           source file.
  --yes                    Reply 'yes' to all automated prompts.
  --validate               Check if files are formatted without changing them.
  --stdin                  Read from stdin, output to stdout.
  --elm-version VERSION    The Elm version of the source files being formatted.
                           Valid values: 0.16, 0.17, 0.18. Default: 0.18
  --upgrade                Upgrade older Elm files to Elm 0.18 syntax

Examples:
  elm-format Main.elm                     # formats Main.elm
  elm-format Main.elm --output Main2.elm  # formats Main.elm as Main2.elm
  elm-format src/                         # format all *.elm files in the src directory

Full guide to using elm-format at <https://github.com/avh4/elm-format>
```

**Comment by Rolograaf** [comment]
Sorry about that Aaron,

Renamed `elm-format.exe`, did an `npm uninstall -g elm-format` than a `npm install -g elm-format` and it tells me:
![npm-install](https://cloud.githubusercontent.com/assets/6130902/24590267/84fbec98-17ea-11e7-8363-9718cad9c9fb.gif)
checking version it gives me old:
![check-version](https://cloud.githubusercontent.com/assets/6130902/24590277/a1899932-17ea-11e7-8930-e83d726234de.gif)
renaming the downloaded file back to `elm-format.exe`
![directory](https://cloud.githubusercontent.com/assets/6130902/24590285/b8a8d51a-17ea-11e7-8b23-53dee22b7b10.gif)
gives me new version
![correct](https://cloud.githubusercontent.com/assets/6130902/24590291/e290336e-17ea-11e7-842c-0e1f4326517b.gif)
and `where` gives me both the `.cmd` and the `.exe`
![cmd-exe](https://cloud.githubusercontent.com/assets/6130902/24590313/3063d2d0-17eb-11e7-82ca-0c96a2b19169.gif)

**Comment by avh4** [comment]
hmm, in the first screenshot, npm is clearly installing version 0.5.2 of the npm package.  
![screen shot 2017-04-02 at 1 28 14 pm](https://cloud.githubusercontent.com/assets/1222/24590785/4fcd9298-17a8-11e7-8b98-ce9e3bfadca1.png)

I guess I don't understand enough about npm.  Why would it not install the latest version?  Does it not always check for new versions?

Does it work if you try

`npm install -g elm-format@latest`

or 

`npm install -g elm-format@0.6.0-alpha.6`

**Comment by Rolograaf** [comment]
Thank you Aaron @avh4  for all your efforts!

First suggestion `@latest` had not the desired outcome
![latest](https://cloud.githubusercontent.com/assets/6130902/24670119/2f7ecd74-196d-11e7-9188-e94006e68aec.gif)
however explicitly naming the version `@0.6.0-alpha.6` did the job
![exact](https://cloud.githubusercontent.com/assets/6130902/24670150/4e9f05c0-196d-11e7-815a-03df71e7a77c.gif)
and the `elm-format.cmd` does it's work as it should
![where](https://cloud.githubusercontent.com/assets/6130902/24670168/5ed7b37e-196d-11e7-8899-44efb20e4c47.gif)

**Comment by avh4** [comment]
Okay, thanks!  

If anyone has more info on why npm would install an old version, let me know.
