### ISSUE TITLE
suggestion: use half indent for `let` and `in` keywords to make diffs better

### ISSUE THREAD

**Issue by norpan** [avh4/elm-format#346]
The basic problem is this. Changing from
```
function =
    functionBody
```
to
```
function =
    let
        helper =
            x
    in
        functionBody
```
will mark the whole functionBody as changed because of indentation. Changing elm-format to do
```
function =
  let
    helper =
        x
  in
    functionBody
```
would make that problem go away.

**Comment by avh4** [comment]
#350 was implemented for 0.6.2-alpha (or more likely will be called 0.7.0-alpha).  We can revisit this once we see how that works in the wild.
