### ISSUE TITLE
Reduce VCS Diff Noise when introducing a `let`?

### ISSUE THREAD

**Issue by rtfeldman** [avh4/elm-format#350]
## The Problem

Consider [`viewEntries`](https://github.com/rtfeldman/elm-todomvc/blob/166e5f2afc704629ee6d03de00deac892dfaeed0/Todo.elm#L253) from TodoMVC. (No need to read all of it; we'll go over particular lines next.)

```elm
viewEntries : String -> List Entry -> Html Msg
viewEntries visibility entries =
    let
        isVisible todo =
            case visibility of
                "Completed" ->
                    todo.completed

                "Active" ->
                    not todo.completed

                _ ->
                    True

        allCompleted =
            List.all .completed entries

        cssVisibility =
            if List.isEmpty entries then
                "hidden"
            else
                "visible"
    in
        section
            [ class "main"
            , style [ ( "visibility", cssVisibility ) ]
            ]
            [ input
                [ class "toggle-all"
                , type_ "checkbox"
                , name "toggle"
                , checked allCompleted
                , onClick (CheckAll (not allCompleted))
                ]
                []
            , label
                [ for "toggle-all" ]
                [ text "Mark all as complete" ]
            , Keyed.ul [ class "todo-list" ] <|
                List.map viewKeyedEntry (List.filter isVisible entries)
            ]
```

Today `viewEntries` looks like this, but let's rewind time to a hypothetical earlier implementation...one where we had not yet introduced that `let` binding:

```elm
viewEntries : String -> List Entry -> Html Msg
viewEntries visibility entries =
    section
        [ class "main" ]
        [ input
            [ class "toggle-all"
            , type_ "checkbox"
            , name "toggle"
            ]
            []
        , label
            [ for "toggle-all" ]
            [ text "Mark all as complete" ]
        , Keyed.ul [ class "todo-list" ] <|
            List.map viewKeyedEntry entries
        ]
```

We commit this to version control. Then later, we add the `allCompleted` functionality like so:

```elm
viewEntries : String -> List Entry -> Html Msg
viewEntries visibility entries =
    let
        allCompleted =
            List.all .completed entries
    in
        section
            [ class "main" ]
            [ input
                [ class "toggle-all"
                , type_ "checkbox"
                , name "toggle"
                , checked allCompleted
                , onClick (CheckAll (not allCompleted))
                ]
                []
            , label
                [ for "toggle-all" ]
                [ text "Mark all as complete" ]
            , Keyed.ul [ class "todo-list" ] <|
                List.map viewKeyedEntry entries
            ]
```

Here's what we did:

1. Add `allCompleted` in a `let` binding.
2. Add `checked allCompleted` to the `input`.
3. Add `onClick (CheckAll (not allCompleted))` to the `input`.

Really minor change.

However, here's the VCS diff of this change:

```diff
 viewEntries : String -> List Entry -> Html Msg
 viewEntries visibility entries =
-    section
-        [ class "main" ]
-        [ input
-            [ class "toggle-all"
-            , type_ "checkbox"
-            , name "toggle"
+    let
+        allCompleted =
+            List.all .completed entries
+    in
+        section
+            [ class "main" ]
+            [ input
+                [ class "toggle-all"
+                , type_ "checkbox"
+                , name "toggle"
+                , checked allCompleted
+                , onClick (CheckAll (not allCompleted))
+                ]
+                []
+            , label
+                [ for "toggle-all" ]
+                [ text "Mark all as complete" ]
+            , Keyed.ul [ class "todo-list" ] <|
+                List.map viewKeyedEntry entries
             ]
-            []
-        , label
-            [ for "toggle-all" ]
-            [ text "Mark all as complete" ]
-        , Keyed.ul [ class "todo-list" ] <|
-            List.map viewKeyedEntry entries
-        ]
```

This happened because we had to indent everything after `in` - creating a flood of VCS diff noise that make it impossible to tell which line(s) in the `Html` actually changed. This diff is useless.

This can be even worse when we want to add a `let` to an `update` function. We have to indent the entire case-expression, even if we're only modifying a branch or two. The diff is even more gigantic and useless.

I've run into this on a fairly regular basis in Elm, and it's been a source of periodic frustration. Considering Elm's style guide already has rules that exist primarily to dodge less impactful VCS diff problems (for example, putting a newline after every `foo =` to avoid VCS diffs caused by switching from single-line to multiline), this seems worth addressing.

## Alternative Formattings

There are a few ways that style guide changes could resolve this VCS diff issue.

One would be to have `elm-format` [indent let-expressions differently from how it indents everything else](https://github.com/avh4/elm-format/issues/346). However, introducing the inconsistency of "half-indents for let-expressions only" seems like an undesirable hack to have in Elm's style guide. Beginners might report it as a bug in `elm-format`.

Another would be to preemptively "double indent" areas like function bodies that are prone to wanting `let` at a later time:

```elm
viewEntries visibility entries =
        section
            [ class "main" ]
            ...
```

Beginners would almost certainly report this as a bug in `elm-format`. Assuming it were adopted, this approach would raise the question of whether branches of `if` and `case` expressions should also get double-indented, since they are also prone to wanting `let` at a later time. There might be other candidates as well.

Here's another way:

```elm
viewEntries visibility entries =
    let
        allCompleted =
            List.all .completed entries 
    in section
        [ class "main" ]
        ...
```

This is a "less bad" approach; the VCS diff would include 1 spurious line (`in section`) rather than N spurious lines.

## Proposed Solution

The most consistent solution seems to be formatting it like this:

```elm
viewEntries visibility entries =
    let
        allCompleted =
            List.all .completed entries 
    in
    section
        [ class "main" ]
        ...
```

Here's the VCS diff from this version:

```diff
 viewEntries : String -> List Entry -> Html Msg
 viewEntries visibility entries =
+    let
+        allCompleted =
+            List.all .completed entries
+    in
     section
         [ class "main" ]
         [ input
             [ class "toggle-all"
             , type_ "checkbox"
             , name "toggle"
+            , checked allCompleted
+            , onClick (CheckAll (not allCompleted))
             ]
             []
         , label
```

Much clearer!

Here's [how TodoMVC would look if reformatted in this style](https://github.com/rtfeldman/elm-todomvc/blob/78e480cbee633f0a9bb605ef4eb0ab37bc0ae34a/Todo.elm).

Thoughts?

**Comment by egauderman** [comment]
I think this is a good proposal.  I'll add that I think this is also good for people who don't use elm-format.

If you're manually indenting and un-indenting, it's a lot of work to have to select and indent/unindent a huge block if you're adding and removing let-bindings while iterating quickly.

**Comment by tekul** [comment]
Has indenting `let` and `in` by two spaces also been considered as an option (similar to the way `where` is often used in Haskell)? This would allow both code blocks to be indented by the same standard four spaces.

**Comment by avh4** [comment]
Implemented in f51590b1...b9d179ac

**Comment by danny-andrews** [comment]
Seems like we're hyper optimizing for diff readability, to the detriment of source readability...the [style guide](http://elm-lang.org/docs/style-guide) states "Goal: a consistent style that is easy to read and produces clean diffs." I think that order is important:
1. Easy to read.
2. Produces clean diffs.
This change made code more difficult to read.

---

Sorry for noise on a closed issue. Just couldn't help myself.

**Comment by ehamberg** [comment]
(Since this still has the “discussion” label… 😉)

Before putting too much weight on diff readability, one should also consider that diff tools – including the `git` command line and GitHub – can be told to ignore white-space changes, which is great for the exact scenario mentioned above where on has white-space changes mixed with “real” changes.

This is how the change in `elm-format` diff looks when _showing_ white-space changes:

https://github.com/avh4/elm-format/compare/f51590b1dad6b5bf167952af0f8ec3ef81f56ba8...b9d179ac759d784e0125f2de694e863323f3489e

… and this is how it looks when _ignoring_ whitespace changes:

https://github.com/avh4/elm-format/compare/f51590b1dad6b5bf167952af0f8ec3ef81f56ba8...b9d179ac759d784e0125f2de694e863323f3489e?w=1

**Comment by rtfeldman** [comment]
> This change makes code more difficult to read (or at least inconsistent).

How so?

**Comment by danny-andrews** [comment]
```elm
foo x =
  let
    y = -- Why do I indent after `let` keyword
      x + 1
  in
  y + 2 -- But not `in`? What makes it so special?
```

**Comment by rtfeldman** [comment]
There has never been a one-size-fits-all rule for indentation after keywords. For example, we indent right after `let` and `else` but not right after `if` and `case`.

There is a clear upside to having `in` in the "do not indent" group: diffing. I don't understand what the upside would be to putting it in the "indent" group instead.

**Comment by danny-andrews** [comment]
> we indent right after `let` and `else` but not right after `if` and `case`.

I don't know what you mean.

Not according to the style guide.
```elm
evaluate : Boolean -> Bool
evaluate boolean =
  case boolean of
    Literal bool ->
        bool

    Not b ->
        not (evaluate b)

    And b b_ ->
        evaluate b && evaluate b_

    Or b b_ ->
        evaluate b || evaluate b_
```

Or the syntax example for conditionals:
```elm
if key == 40 then
    n + 1

else if key == 38 then
    n - 1

else
    n
```

**Comment by rtfeldman** [comment]
```elm
if
    foo
```

```elm
case
    foo
```

```elm
else
    foo
```

```elm
in
    foo
```

All of these are syntactically valid. `elm-format` indents some of them this way, and others it indents differently.

I understand that you think it looks better with the value after `in` indented.

My point is that there is nothing **inconsistent** about formatting it this way. There have always been different rules for how indentation does or does not happen after different keywords.

**Comment by danny-andrews** [comment]
I think you missed my point. In the case of `if` and `case` elm-format **doesn't indent at all**. In fact, it will remove indentation if there exists any, in order to put what follows on the same line as the keyword.

```elm
-- Before
a = if
  key == 40 then
    n + 1
else
  n

-- After
if
  key == 40 then
    n + 1
else
  n
```

My point is: any time `elm-format` **breaks a line of code onto a newline** directly after a keyword, it indents one level.

`elm-format` output:

```elm
then
  foo

else
   foo

of
  foo

let
  foo

in
foo // wtf!?
```

If you can show me a counterexample, then I'll agree there's nothing **inconsistent** about formatting it this way.

**Comment by danny-andrews** [comment]
One last note: optimizing for diff readability in Elm really seems like a waste of effort. One of the main selling-points of Elm is that you can be confident when you change code. In [Tereza's talk](https://youtu.be/a0039_JRAQo?t=10m26s) she talks about a refactor she did across **100 files**. I **highly** doubt the person who reviewed that PR scored every line of the diff output.

If there is ever the slightest conflict between source readability and diff readability (as in this case) source readability should win.

**Comment by avh4** [comment]
I've just read through the recent message here, and I'm not sure what's being discussed.  This issue is closed because it was implemented.  If there's a new issue to discuss, please create a new issue for it and and give a clear example of what change you're proposing.  Thanks!
