### ISSUE TITLE
File does not exist WebStorm/Windows

### ISSUE THREAD

**Issue by andreydos** [avh4/elm-format#351]
I have configured elm-format in WebStorm (as shown in https://github.com/avh4/elm-format/blob/master/img/JetBrains%20setup.png) and get such error "There was a problem reading one or more of the specified input files: yes: File does not exist"
![7a074-clip-70kb](https://cloud.githubusercontent.com/assets/13402400/25117938/c6acf392-241c-11e7-91da-f812f1204064.png)
"

**Comment by avh4** [comment]
It looks like you set the arguments incorrectly in the watcher configuration.  It should be

`--yes $FilePath$`

with no space between the dashes and the `yes`

**Comment by andreydos** [comment]
@avh4 Thanks a lot! That's my bad.
