### ISSUE TITLE
Should parens be removed around negative variable references?

### ISSUE THREAD

**Issue by avh4** [avh4/elm-format#370]
I used to sometimes write `f (-n)` to make it clear that it's not `f - n`.  Do we really want to remove the parens here and leave `f -n`?  I feel like we do want to remove the parens for numbers, but for some reason I'm hesitant about doing it for var references.

**Comment by avh4** [comment]
I think it's probably best not to add special exceptions at this point.

**Comment by rtfeldman** [comment]
I've always written `f (negate n)`, but that is in no small part because I did not know `-n` was a thing in Elm. 😅

**Comment by avh4** [comment]
Interesting.. maybe unary minus is something that should be removed from Elm as unnecessary syntax.  It certainly makes the parser more complex, and the parsing of negative literals alone would be a lot simpler.

**Comment by rtfeldman** [comment]
I like that idea! ☝️ cc @evancz

**Comment by avh4** [comment]
I guess the other place people are used to having unary minus is with parens: `a * -(x +y)`
