### ISSUE TITLE
let followed by if looks odd in exp

### ISSUE THREAD

**Issue by BrianHicks** [avh4/elm-format#371]
I've just installed `@exp` and tried it out. The first thing I noticed was that `let` followed by `if` looks odd. If I'm reading the changelog correctly, unindenting let bodies was intentional? I'm not sure, so I'm opening an issue.

Regardless, this particular case made me raise an eyebrow; the indentation made sense to me.

SSCCE:

```elm
module Test exposing (..)


letAndIf : Int
letAndIf =
    let
        x =
            1
    in
    if x == 1 then
        x
    else
        100
```

**Comment by ianmackenzie** [comment]
It looked odd to me too initially, but I'm pretty quickly starting to like it. I like how the new formatting emphasizes the final expression over the subordinate expressions inside the 'let' block, and it cuts down on excessive indentation when you use nested 'let' expressions. To take a real example from some of my own code with new formatting:

```elm
lengthAndDirection : Vector2d -> Maybe ( Float, Direction2d )
lengthAndDirection vector =
    let
        vectorLength =
            length vector
    in
    if vectorLength == 0.0 then
        Nothing
    else
        let
            normalizedVector =
                scaleBy (1 / vectorLength) vector

            vectorDirection =
                Direction2d (components normalizedVector)
        in
        Just ( vectorLength, vectorDirection )
```

I think the new formatting does a good job here of emphasizing the important if/else logic over the computation of auxiliary values like `vectorLength` and `normalizedVector` (the `Nothing` and the `Just` end up vertically aligned, which is nice), and it generally looks a little less 'spidery' than the old version:

```elm
lengthAndDirection : Vector2d -> Maybe ( Float, Direction2d )
lengthAndDirection vector =
    let
        vectorLength =
            length vector
    in
        if vectorLength == 0.0 then
            Nothing
        else
            let
                normalizedVector =
                    scaleBy (1 / vectorLength) vector

                vectorDirection =
                    Direction2d (components normalizedVector)
            in
                Just ( vectorLength, vectorDirection )
```

**Comment by rtfeldman** [comment]
Something I just realized: now when you look at value both branches of the `if` evaluate to, they line up.

```elm
    if vectorLength == 0.0 then
        Nothing
    else
        let
            ...
        in
        Just ( vectorLength, vectorDirection )
```

**Comment by rtfeldman** [comment]
Incidentally, here was the original issue that led to the change in `let` formatting: https://github.com/avh4/elm-format/issues/350

**Comment by avh4** [comment]
This is expected in 0.7.0-exp.  It does look weird, but that was weighed against the benefit of reducing unnecessary diffs when adding let expressions.  If you have an alternative format to suggest, open a new issue for discussion of the suggestion.
