### ISSUE TITLE
binwrap-install balks on installing on Linux (maybe permissions problem?)

### ISSUE THREAD

**Issue by dannyob** [avh4/elm-format#377]
When I try `sudo npm -g install elm-format@exp` on my Debian linux setup, I get an EACCES error, thusly:

```
: lifeboat  ~public/lifehacking/statbot%; sudo npm install -g elm-format@exp
/usr/bin/elm-format -> /usr/lib/node_modules/elm-format/bin/elm-format

> elm-format@0.7.0-exp install /usr/lib/node_modules/elm-format
> binwrap-install

fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open 'bin/elm-format'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.writeFileSync (fs.js:1347:33)
    at /usr/lib/node_modules/elm-format/node_modules/binwrap/install.js:17:8
    at Array.forEach (native)
    at install (/usr/lib/node_modules/elm-format/node_modules/binwrap/install.js:15:19)
    at Object.install (/usr/lib/node_modules/elm-format/node_modules/binwrap/index.js:8:14)
    at Object.<anonymous> (/usr/lib/node_modules/elm-format/node_modules/binwrap/bin/binwrap-install:16:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
```

npm debug log attached!

[npm-debug-log.txt](https://github.com/avh4/elm-format/files/1050795/npm-debug-log.txt)

**Comment by alexgig** [comment]
I saw the same on macOS Sierra when installing with node 8, npm 5.

Downgrading to node 6, npm 3 worked.

**Comment by battermann** [comment]
I have the same issue on Elementary OS. @alexgig 's workaround seems to work.

**Comment by no-stack-dub-sack** [comment]
I _was_ having the same issue on Mac OSX Sierra with Node 8 and NPM 5... decided to try installing with yarn just for kicks, and it worked no problem. Might be worth a shot if anyone is still having an issue - not really addressing the root of the problem, but seems to do the trick. c

**Comment by no-stack-dub-sack** [comment]
I _was_ having the same issue on Mac OSX Sierra with Node 8 and NPM 5... decided to try installing with yarn just for kicks, and it worked no problem. Might be worth a shot if anyone is still having an issue - not really addressing the root of the problem, but seems to do the trick. c

**Comment by qqrs** [comment]
Similar issue on Mac OS X. 

npm install of `elm-format` was also hanging for me at`binwrap-install`.

```
$ npm install -g elm-format
/usr/local/bin/elm-format -> /usr/local/lib/node_modules/elm-format/bin/elm-format

> elm-format@0.6.1-alpha install /usr/local/lib/node_modules/elm-format
> binwrap-install
```

Yarn also failed.
```
$ yarn global add elm-format
yarn global v1.2.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[1/1] ⠠ elm-format
[-/1] ⠠ waiting...
[-/1] ⠠ waiting...
[-/1] ⠠ waiting...
^C/1] ⠠ waiting...
```

But it succeeded when I ran with verbose logging.
```
$ npm install -g elm-format --loglevel=verbose
```

I had run it several times without verbose logging, and I don't think I changed anything that would have fixed it, so it is odd that changing the loglevel fixed it.

**Comment by crankbird** [comment]
I tried npm install -g elm-format --loglevel=verbose which still failed so I tried yarn instead

That also exhibited the waiting behaviour you noted above .. however after about 10-15 seconds it resolved itself 

yarn global v1.3.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Installed "elm-format@0.6.1-alpha" with binaries:
      - elm-format
✨  Done in 18.20s.

Mine uses a later version of yarn, but I suspect that yarn may have fixed some underlying stuff before it hung on your machine allowing the subsequent nom install to work, if I were to guess it would be the step 3 .. linking dependencies, but thats just a guess.

 the --loglevel probably had nothing to do with it, though that's just a conjecture.

**Comment by zainhoda** [comment]
Yarn worked for me pretty quickly

```
$ yarn global add elm-format
yarn global v1.3.2
[1/4] 🔍  Resolving packages...
warning elm-format > binwrap > unzip > fstream > graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Installed "elm-format@0.6.1-alpha" with binaries:
      - elm-format
✨  Done in 3.82s.

```

**Comment by psfblair** [comment]
For macOS, the reason for this is that nom tries to install elm under /usr/lib instead of /usr/local/lib. That's a directory protected by System Integrity Protection (SIP) which isn't writable even with sudo. (See https://apple.stackexchange.com/questions/237778/cant-write-to-usr-even-with-sudo). The fix is to use /usr/local instead. Yarn installs in /usr/local, which avoids the problem.

**Comment by psfblair** [comment]
On macOS, this seems to have something to do with the System Integrity Protection that keeps certain directories from being writable even with sudo. I got around the problem this way:
$> mkdir ~/.npm-global
$> sudo npm config set prefix '~/.npm-global'
$>  vi ~/.profile 
# Add ~/.npm-global/bin to PATH
$> source ~/.profile
$> npm install -g elm

**Comment by rtfeldman** [comment]
@dannyob This is a general `npm` issue - they have an explanation for how to deal with it: https://docs.npmjs.com/getting-started/fixing-npm-permissions

As a quick tip, I would recommend never running `sudo npm` in general! 😄

**Comment by avh4** [comment]
The next release (0.8.6) will use a new npm publishing technique (the same one now used by the elm compiler).  Please open a new issue after 0.8.6 if there are still problems.

**Comment by lydell** [comment]
> the same one now used by the elm compiler

The same one _potentially used by the elm compiler in the future:_ https://github.com/elm/compiler/pull/2287
