### ISSUE TITLE
elm-format automatically removing intentional redundant braces

### ISSUE THREAD

**Issue by mordrax** [avh4/elm-format#383]
One thing I've noticed in the elm-format@exp branch is that it is removing braces around code which it knows is not needed due to operator precedence rules.

However, my position is that I don't know and do not care particularly to remember all the infix operator precedence rules but I intentionally add braces to remove any ambiguity of what is happening on a line of code.

By removing braces, it forces me to understand and remember operator precedence rules and it means that anyone not familiar with the code will also have to learn it.

My current workaround, would be to capture partial calculations in their own variables, which isn't necessarily a bad thing.

I'm of two minds about this because in some places, removing extra braces is a great thing.

**Comment by avh4** [comment]
Currently, elm-format does not change parenthesis within sequences of binary operators.  Any parentheses you for binary operator precedence should not be changed.

**Comment by mordrax** [comment]
I've been playing around with elm-format@exp ( fulltime in the last two weeks ) and am loving it. In practice, this issue only occurred once for me which prompted me to raise it, however, I'm happy to leave it as it is and close it. 

If I find a concrete example of said ambiguity, I will raise a better issue.
