### ISSUE TITLE
blank lines separate if/else clauses

### ISSUE THREAD

**Issue by avh4** [avh4/elm-format#393]
(Change requested by Evan)

`if` expressions should have a  blank line before each clause.

```elm
if True then
    a

else
    b
```

**Comment by rtfeldman** [comment]
I seem to recall we discussed this waaaaaay back in the day, like circa the initial release maybe.

I forget why we went the other way, but either style is cool with me. 👍

**Comment by gyzerok** [comment]
Should this change first come within "exp" release?

**Comment by lydell** [comment]
I can see that there's a blank line above `else` in the example, but what does "a blank line **before each clause**" mean?

**Comment by avh4** [comment]
Fixed in 80c50e6...1e68e19

**Comment by frou** [comment]
Is the general push for massive amounts of vertical whitespace explained anywhere?
