### ISSUE TITLE
Handle section newlines in record types

### ISSUE THREAD

**Issue by mark-jordanovic-lewis** [avh4/elm-format#396]
I am currently refactoring my state models by flattening out nested models and implementing extensible records. I want to separate the sections of a large state model with comments but I'm getting some bad style after beautification:
> desired
```type alias State =
  { -- things from column a
    thingOne : Thing
  , thingTwo: Thing
    -- things from column b
  , thingThree : Thing
  , thingFour : Thing
  }
```
> beautified
```type alias State =
  { -- things from column a
    thingOne : Thing
  , thingTwo: 
      Thing     <-- this is annoying
    -- things from column b
  , thingThree : Thing
  , thingFour : Thing
  }
```
my state is obviously a lot bigger than this and these new lines break up the flow of reading it. ~~I'll be happy to have a bash at fixing this, if someone can point me to the correct file this is handled in.~~ I found the location of the files and it's beyond my Haskell knowledge.

**Comment by avh4** [comment]
Ah, does it work correctly for record values/expressions?  The handling of section comments might not be implemented yet for record _types_.

Yeah, the code for this won't be trivial because it depends on changes to the parser as well as to the formatter.

**Comment by mark-jordanovic-lewis** [comment]
It's nice for instantiating, only sectioning when declaring records produces this.

Yeah, that was the conclusion of my investigation into trying to monkey patch it before I hit too many & and $ for me to understand. I'm doing a course on Haskell in about a month, if you don't have time for it I'll fork and give it a bash then. For now it's ok, it's just a small bug that we can deal with.

**Comment by avh4** [comment]
elm-format-0.7.0-exp formats the original example as:

```
type alias X =
    { -- things from column a
      thingOne : Thing
    , thingTwo : Thing

    -- things from column b
    , thingThree : Thing
    , thingFour : Thing
    }
```

So I think this is already implemented.
