### ISSUE TITLE
Cannot use non-aliased type with JSON decoder

### ISSUE THREAD

**Issue by tuxagon** [avh4/elm-format#401]
I was working on a decoder and decided to not use `type alias` for a particular piece of JSON. `elm-format` would keep changing `{ data : List Item }` to `{ data = List Item }`

In context expected
```
import Json.Decode
import Json.Decode.Pipeline

type alias Item =
    { id : Int
    , name : String
    }

decodeItems : Json.Decode.Decoder { data : List Item }
decodeItems =
    Json.Decode.Pipeline.decode { data : List Item }  -- offending line
        |> (Json.Decode.Pipeline.required "data" (Json.Decode.list decodeItem))

decodeItem : Json.Decode.Decoder Item
decodeItem =
    Json.Decode.Pipeline.decode Item
        |> Json.Decode.Pipeline.required "id" Json.Decode.int
        |> Json.Decode.Pipeline.required "name" Json.Decode.string
```

In context actual
```
import Json.Decode
import Json.Decode.Pipeline

type alias Item =
    { id : Int
    , name : String
    }

decodeItems : Json.Decode.Decoder { data : List Item }
decodeItems =
    Json.Decode.Pipeline.decode { data = List Item }  -- offending line
        |> (Json.Decode.Pipeline.required "data" (Json.Decode.list decodeItem))

decodeItem : Json.Decode.Decoder Item
decodeItem =
    Json.Decode.Pipeline.decode Item
        |> Json.Decode.Pipeline.required "id" Json.Decode.int
        |> Json.Decode.Pipeline.required "name" Json.Decode.string
```

Ultimately, it's probably better to use a type alias; however, this does still seem like a bug.

**Comment by avh4** [comment]
`{ data : List Item }` is not a valid Elm expression (it is only a valid Elm type).

Your original code is not valid, according to `elm-compiler`/`elm-make`.

**Comment by basile-henry** [comment]
@tuxagon When you use a type alias, it also provides you with a "constructor" (of the same name) for the type. So for example if you used:

```elm
type alias Data = { data : List Item }
```

You can then use the function `Data` which has the following type:

```elm
Data : List Item -> Data
```

This function is what is used in the decode pipeline. If you want to use the JSON decode pipeline without aliases, no problem, you just need to provide a function that acts as a constructor for your record. For example the following anonymous function should work:

```elm
\x -> { data = x }
```

In your example it could look like this:

```elm
Json.Decode.Pipeline.decode (\data -> { data = data })  -- offending line
        |> (Json.Decode.Pipeline.required "data" (Json.Decode.list decodeItem))
```

**Comment by tuxagon** [comment]
Thanks! That makes perfect sense. I should have realized that initially.
