### ISSUE TITLE
Merge concatenated list literals?

### ISSUE THREAD

**Issue by rtfeldman** [avh4/elm-format#402]
[`elm-analyse`](https://github.com/stil4m/elm-analyse) gives a warning for this situation:

> If you concatenate two lists `([...] ++ [...])`, then you can merge them into one list.

This seems like a stylistic concern, and a reasonable one at that!

I can't think of any situations where it would be clearer to write `[ foo ] ++ [ bar ]` than `[ foo, bar ]`. Should `elm-format` automatically merge two concatenated list literals like this?

**Comment by stil4m** [comment]
@rtfeldman I think this would be currently blocked by [this bug](https://github.com/elm-lang/elm-compiler/issues/1521). A valid workaround for that issue is to split the literal lists into multiple sublists.

**Comment by rtfeldman** [comment]
Good point, although I believe that one is fixed in 0.19!

**Comment by jfmengels** [comment]
`elm-review` handles this well, which I think is a good compromise. I don't think `elm-format` should be the one doing this change.

**Comment by avh4** [comment]
As noted previously, https://package.elm-lang.org/packages/jfmengels/elm-review-simplify/latest/ can do this, and I have not seen any disagreement recently that this would be better handled by elm-format over elm-review.
