### ISSUE TITLE
Merge cons'd list literals

### ISSUE THREAD

**Issue by rtfeldman** [avh4/elm-format#403]
[`elm-analyse`](https://github.com/stil4m/elm-analyse) gives a warning for this situation:

> If you cons an item to a literal list `(x :: [1, 2, 3])`, then you can just put the item into the list.

This seems like a stylistic concern, and a reasonable one at that!

I can't think of any situations where it would be clearer to write `foo :: [ bar ]` than `[ foo, bar ]`. Should `elm-format` automatically merge this into a single list literal?

**Comment by jfmengels** [comment]
`elm-review` handles this well, which I think is a good compromise. I don't think `elm-format` should be the one doing this change.

**Comment by avh4** [comment]
As noted previously, https://package.elm-lang.org/packages/jfmengels/elm-review-simplify/latest/ can do this, and I have not seen any disagreement recently that this would be better handled by elm-format over elm-review.
