### ISSUE TITLE
Whitespace stripped from multiline strings

### ISSUE THREAD

**Issue by hillerstorm** [avh4/elm-format#437]
Sometimes whitespace is significant inside a multiline string and it seems weird to me that `elm-format` has a say in what I can and cannot put inside my own strings :)

This may be a silly example but the following is an input string for a coding advent calendar (advent of code 2017) and it represents a maze of sorts. What bothers me is that I can't paste the example-grid straight into a multiline string and expect it to stay the way it was written.

This code (before formatting):
```Elm
input : String
input =
    """     |          
     |  +--+    
     A  |  C    
 F---|----E|--+ 
     |  |  |  D 
     +B-+  +--+ 
                
"""
```

becomes this after running `elm-format` on it:
```Elm
input : String
input =
    """     |
     |  +--+
     A  |  C
 F---|----E|--+
     |  |  |  D
     +B-+  +--+

"""
```

It may not look like much but all trailing whitespace including that last line of 16 spaces is trimmed away :)
I can see this being an issue when trying to test exact user input as well, since you can't trust what you paste into a string to be the same thing you copied.

I also have an issue with tabs not being an accepted character in strings but that's more of an `elm-compiler` issue ;)

**Comment by lydell** [comment]
Hehe, I'm doing Advent of Code 2017 in Elm as well and just encountered exactly the same thing. I took it as an exercise to automatically pad each line using code though ;)

I also noticed that tabs cannot be used inside strings in another day of AoC :)

**Comment by avh4** [comment]
Fixed in f17ee91, and will be included in elm-format-0.8.0 (will be released shortly after Elm 0.19 is released)

**Comment by lydell** [comment]
Should we open a new issue about tabs inside strings?

**Comment by avh4** [comment]
I believe elm-compiler does not allow literal tabs, even within strings, so I don't think there is anything useful elm-format can do about tabs.

**Comment by lydell** [comment]
Ok, thanks!
