### ISSUE TITLE
Add version number to readme / reduce emphasis on exp build

### ISSUE THREAD

**Issue by simonh1000** [avh4/elm-format#449]
The main read me has no reference to the current version number, and the only install instructions are for the experimental version (which I presume is even more cutting edge than the alpha description of the projection as a whole). it would be great if the readme got new users on to the latest non-experimental version

**Comment by avh4** [comment]
I agree in general, though the 0.7.0-exp features are all approved, so its style should be considered official now.  The 0.7.1 (not experimental) release is overdue, and there likely won't be another exp release until after 1.0.0

**Comment by avh4** [comment]
Fixed in https://github.com/avh4/elm-format/pull/524 for the 0.8.0 release.
