### ISSUE TITLE
Time for release?

### ISSUE THREAD

**Issue by ilovezfs** [avh4/elm-format#456]
I notice "It's almost time for a stable release of elm-format" in the description of https://github.com/avh4/elm-format/releases/tag/0.7.0-exp

Since that was back in May 2017, I'm wondering if it's time for that stable release to happen.

**Comment by avh4** [comment]
Yep, the remaining issues for 0.7.1 (not an exp release) are here: https://github.com/avh4/elm-format/milestone/22

**Comment by ilovezfs** [comment]
@avh4 while I have your attention, in Homebrew currently we ship 0.6.1-alpha. Usually we don't ship any software that is not considered stable by its upstream, but elm-format was grandfathered in due to the deprecation of the https://github.com/Homebrew/homebrew-devel-only repository. Is it your preference that we continue to ship 0.6.1-alpha? Or should we start distributing 0.7.0-exp instead? That's really what I was getting at with this issue.

**Comment by avh4** [comment]
Yeah, it's a good question in general of whether the `exp` releases should be published as packages (on homebrew and elsewhere).  In npm, we 0.6.1 is the default version, but users can request to install `elm-format@exp` which will give the latest exp version-- does homebrew support something like that?  elm-format seems to be an unusual project in that the `exp` releases are not unstable, but are simply UI and formatting changes that are being tried in the wild.

At present, I think it's best to keep 0.6.1 as the default homebrew version.  0.7.1-beta is the next release (and will be forced by the upcoming release of Elm 0.19), so at the point there will be no `exp` version for a while.

**Comment by avh4** [comment]
I think this discussion is resolved?  elm-format-0.8.0-beta will be released when Elm 0.19 is released (or possibly sooner).  At that time, users of both elm-format-0.6 and elm-format-0.7-exp should upgrade to elm-format-0.8.
