### ISSUE TITLE
Add `exposing` if `module X (Y)`

### ISSUE THREAD

**Issue by ahstro** [avh4/elm-format#467]
It would be nice if elm-format could convert
```
module Foo (Bar)

import Bar (Foo)
```
to
```
module Foo exposing (Bar)

import Bar exposing (Foo)
```
on a save, similarly to how it converts
```
foo =
    { bar : "foobar"
    }
```
to
```
foo =
    { bar = "foobar"
    }
```

It would let you save some some typing, and maybe help some people either used to, or hopping back and forth between Haskell. I don't know if it's out-of-scope for what elm-format wants to be, but since it felt similar to the record example, I thought it worth creating an issue.

**Comment by basile-henry** [comment]
If it's meant for people coming form Haskell, shouldn't it be:

```haskell
module Foo (Bar) where
```

to

```elm
module Foo exposing (Bar)
```

**Comment by ahstro** [comment]
@basile-henry Well, I suppose both would be fine with me, I mainly wanted it because I'm lazy

**Comment by kutyel** [comment]
`module` case is already working, I drafted a PR in progress... (thanks @avh4 for the pair programming!) as soon as I fix the `import` case as well this will be finished! 🚀

**Comment by kutyel** [comment]
Fixed and ready for review! 🙌
