### ISSUE TITLE
elm-upgrade support: convert `Basics.rem` to `remainderBy`

### ISSUE THREAD

**Issue by avh4** [avh4/elm-format#478]

**Comment by avh4** [comment]
Fixed in 851d6a2ccb8bc9eb406c23add7e142efe5675c61

**Comment by matheus23** [comment]
This change introduces bugs, because the name `rem` might not be imported from `Basics`!

For example on this file: https://github.com/chendesheng/webvim/blob/b2f103c8868d7f3de8e53ae38ce506a8226a1303/src/View/Cursor.elm
