### ISSUE TITLE
Enforce vertical formatting of module exports

### ISSUE THREAD

**Issue by gyzerok** [avh4/elm-format#481]
Currently `elm-format` has following behavior:
1. Module exports - `exposing (foo, bar, baz)` - are sorted alphabetically
2. If you move at least one export to the new line they all will be formatted vertically

During work on the 20K+ LOC codebase with 4 devs we discovered that one can get merging conflicts somewhat often, if the formatting of exports is horizontal.

As far as I know one reason to sort imports alphabetically was to reduce possibility of merge conflicts. I believe the same idea could work great for the exports as well. However to make it so, we need to enforce vertical formatting.

What do you think about this?

**Comment by avh4** [comment]
In 0.8.0 and later, module exposing are sorted and grouped in a way that matches the `@docs` lines in your module documentation.  You can use this to group them in lines however you'd like.

**Comment by gyzerok** [comment]
@avh4 yeah, I've noticed this change in the `elm-format` behavior. I do not follow though how this new feature solves my problem.

What I want is layout which will minimize merge conflicts chance. It seems that the solution for this problem for imports was to sort them alphabetically. Just sorting won't work for exports. If they are on the same line merge confilcts will happen anyway. This could be solved with enforced vertical layout.

Of course I could make it by hand, but it is very tedious. And as I understand the idea behind formatting tools is exactly to avoid manual work in such cases.
