### ISSUE TITLE
Handle updating records

### ISSUE THREAD

**Issue by Janiczek** [avh4/elm-format#49]
Minimal failing case:
```elm
update model = { model | x <- "abc" }
```

http://elm-lang.org/docs/records#updating-records

```bash
$ elm-format UpdateRecord.elm --yes
Processing file UpdateRecord.elm
ERRORS
-- SYNTAX PROBLEM --------------------------------------------------- <location>

I ran into something unexpected when parsing your code!


I am looking for one of the following things:

    =
    whitespace
```

**Comment by avh4** [comment]
alpha version will only support 0.16 syntax.  1.0.0 version should be able to parse 0.15 files, but will output 0.16 files (meaning `<-` will change to `=` in record updates).

**Comment by Janiczek** [comment]
So just to clarify: `<-` is "old" syntax and `=` is the new syntax?

**Comment by Janiczek** [comment]
By the way, having this:

`autocmd BufWritePost *.elm silent execute "!elm-format --yes %" | edit! | set filetype=elm`

in my Vim config is absolutely amazing. You save and immediately there's a nice syntax. :)

**Comment by rtfeldman** [comment]
@Janiczek yes, in Elm 0.16 record update syntax is changing to replace `<-` with `=`

**Comment by avh4** [comment]
0.15 is not going to be supported.  Closing this.
