### ISSUE TITLE
Should preserve escaped strings

### ISSUE THREAD

**Issue by avh4** [avh4/elm-format#5]
Currently:

    "\xA0S\xA0"

incorrectly formats as:

    " S "

Should escape the following:
 - `\\`
 - `\n`
 - `\t`
 - `\"` in strings
 - `\'` in chars
 - any whitespace character except a normal space ` ` as `\xNN` or `\xNNNN`
 - any non-print character as `\xNN`, `\xNNNN`, or `\xNNNNN`

Characters not listed above should not be escaped.

**Comment by rtfeldman** [comment]
Particularly important for backslashes in regular expressions:

![screen shot 2015-10-20 at 8 33 15 am](https://cloud.githubusercontent.com/assets/1094080/10612369/5109469c-7705-11e5-9d81-46a95cdf30f8.png)

https://github.com/rtfeldman/dreamwriter/compare/0.16...elm-format#diff-ffe139c99a7880eaab2e54076703eff4L77

**Comment by avh4** [comment]
Fixed in d4569c6 and d4569c6^.
