### ISSUE TITLE
Usage under Nodejs 10.1?

### ISSUE THREAD

**Issue by Qqwy** [avh4/elm-format#502]
elm-format depends on some NPM dependencies who've specified their Node versions as up to and including 9.

I´ ve installed it under 10.1.0 using `yarn global add elm-format --ignore-engines` and until now everything seems fine.

What is the current progress towards an official Nodejs 10 release?

**Comment by avh4** [comment]
What error are you seeing?  Here is what I get when using node 10:


```
$ node --version
    v10.1.0
$ npm --version
    5.10.0
$ npm install elm-format
    npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js

    > elm-format@0.6.1-alpha install [...]/node_modules/elm-format
    > binwrap-install

    + elm-format@0.6.1-alpha
    added 87 packages from 71 contributors in 7.556s
    [+] no known vulnerabilities found [145 packages audited]
$ npx elm-format
    elm-format-0.18 0.6.1-alpha
    ...
$ npm install elm-format@exp
    > elm-format@0.7.0-exp install [...]/node_modules/elm-format
    > binwrap-install

    + elm-format@0.7.0-exp
    updated 1 package in 4.832s
    [+] no known vulnerabilities found [670 packages audited]
$ npx elm-format
    elm-format-0.18 0.7.0-exp
    ...
```

**Comment by Qqwy** [comment]
Interesting. I was using Yarn, but it's strange that this difference between NPM and Yarn exists here:

```bash

$ node --version
v10.1.0
$ npm --version
6.0.1
$ yarn --version
1.6.0
$ yarn global add elm-format
yarn global v1.6.0
(node:872) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.

```

**Comment by avh4** [comment]
upath v1.1.0 appears to be compatible with node 10

**Comment by avh4** [comment]
upath v1.1.0 appears to be compatible with node 10.  Can you upgrade to that version?

**Comment by Qqwy** [comment]
Interesting. Turns out `elm-format` does install without problems when installing locally, but not globally.

I'm guessing `upath` is not part of `elm-format`'s dependencies then. I'll try to upgrade that package separately.

**Comment by avh4** [comment]
I'm not sure what upath is, but it could possibly be a dependency of one of elm-format's dependencies.

**Comment by avh4** [comment]
Node 10 is no longer supported, and the next elm-format (0.8.6) will use a new npm publishing technique.  Please open a new issue after 0.8.6 is released if there is still a problem.
