### ISSUE TITLE
Error message assumes input is a file

### ISSUE THREAD

**Issue by harrysarson** [avh4/elm-format#503]
I misspelt a directory name in the arguments to elm-format and got an error message telling me the file does not exist: 
```bash
$ elm-format elm-test --validate

[There was a problem reading one or more of the specified input files:

    elm-test: File does not exist

Please check the given paths.
```

I would like to suggest changing this error message to (changes emphasised using **): 
```bash
$ elm-format elm-test --validate
[There was a problem reading one or more of the specified input **paths**:

    elm-test: **No such file or directory**

Please check the given paths.
```

This matches the result of `$ stat elm-test`. I am happy to make a PR if this change would be appreciated.

**Comment by avh4** [comment]
Yes, I like your suggested new error message!

However, I think what you are saying should only apply when run without `--validate`.  When run with `--validate`, the output is supposed to always be valid JSON, in this case, it should probably be
```json
[{"path":"elm-test","message":"No such file or directory"}
]
```

I guess there's a separate bug that `--validate` is not printing JSON in this case.

**Comment by avh4** [comment]
Added https://github.com/avh4/elm-format/issues/504 for the JSON issue.
