### ISSUE TITLE
VS code integration does not move cursor to end of line.

### ISSUE THREAD

**Issue by harrysarson** [avh4/elm-format#514]
In the README:

Visual Studio Code | 🏆 Elm Language Support | ⚠️ 3 steps | ❌ formatting moves cursor to end of file | ⚠️ requires configuration | ❔ TBD | ❔ TBD
-- | -- | -- | -- | -- | -- | --

However, I found that this is no longer true:

![vs-code-format-on-save](https://user-images.githubusercontent.com/16308754/43311065-47e81f86-9181-11e8-9b38-9f31fadc64af.gif)

If this is true then the warning can be removed from the README. :smile:

**Comment by avh4** [comment]
Thanks, this was fixed in https://github.com/avh4/elm-format/pull/506
