### ISSUE TITLE
Use Text instead of [Char] for rendering

### ISSUE THREAD

**Issue by avh4** [avh4/elm-format#53]
`src/Box.hs` should be changed to have `render` return `Text` or `LazyText` (which is better?) instead of `[Char]`/`String`.

#52 should probably be done before this.

**Comment by Janiczek** [comment]
Some reading about the decision `Data.Text` vs `Data.Text.Lazy`:
http://stackoverflow.com/questions/24641540/haskell-lazy-vs-strict-text-values-which-one-is-recommended-when
http://blog.ezyang.com/2010/08/strings-in-haskell/

I'm not very well versed in this, but I think a few kilobytes of a program is not a problem for `Data.Text` and `Data.Text.Lazy` is a premature optimization.

Will work on this.

**Comment by avh4** [comment]
Thanks for the research.  Merged!
