### ISSUE TITLE
Indented URLs in doc comments get formatted as code

### ISSUE THREAD

**Issue by rtfeldman** [avh4/elm-format#532]
https://github.com/rtfeldman/elm-css/commit/4839635d5be38ea8d34e61e55e7ff3af855d685b

### Original

```
{-| Selector for a dl element.

    https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl
-}
```

### Formatted

```
{-| Selector for a dl element.

     https :// developer.mozilla.org / en - US / docs / Web / HTML / Element / dl
-}
```

### Workaround

This is easy to fix by wrapping the URL in angle brackets:

```
{-| Selector for a dl element.

    <https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl>
-}
```

I'm open to the possibility that the current behavior should not be changed, but it surprised me, so I thought I'd report it!

**Comment by avh4** [comment]
What was the markdown rendering that you expected from this?  4-space indent means a code block, and a code block without a specified language is interpreted by elm-format as being an Elm code block, and `https :// developer.mozilla.org / en - US / docs / Web / HTML / Element / dl` is a valid Elm expression!

Looking at the current rendering of the docs, you probably just want to have the link in a paragraph, not in a code block:

Current (appears to be syntax highlighting the URL as Elm code):
<img width="661" alt="screen shot 2018-08-28 at 8 39 57 am" src="https://user-images.githubusercontent.com/1222/44734111-03328f80-aa9e-11e8-9cc7-7baacb16ecfe.png">

Probably will render better, with a clickable link:
```elm
{-| Selector for a dl element.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl
-}
```

If you really do want the URL in a code block, you can specify a non-Elm code block like this:
````elm
{-| Selector for a dl element.

```text
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl
```
-}
````

**Comment by rtfeldman** [comment]
Yeah, makes sense - current behavior is probably best.

Just got a comment on a PR that this had gotten reformatted, and thought I'd open an issue about it!
