### ISSUE TITLE
Enforce newline at EOF

### ISSUE THREAD

**Issue by rtfeldman** [avh4/elm-format#54]
In the spirit of "elm-format prevents arguments over which convention to use," automatically guaranteeing a newline at EOF for UNIX tool friendliness and POSIX compliance seems correct: http://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

**Comment by avh4** [comment]
Is this not happening already?

**Comment by rtfeldman** [comment]
Oh, totally possible that it already is and I missed it - just don't remember our discussing it so I thought I'd bring it up...might be this is already closeable!

**Comment by avh4** [comment]
Okay, you definitely had this in the design doc.

In any case, this would make a good QuickCheck test to add.

**Comment by rtfeldman** [comment]
Right, I'm pretty sure I just have an embarrassingly poor memory and this never merited opening in the first place.

I'll just quietly close it, and let us never speak of this again. :stuck_out_tongue_winking_eye:
