### ISSUE TITLE
Extra space inserted in exposing list with comment

### ISSUE THREAD

**Issue by akselw** [avh4/elm-format#544]
As discussed on Slack, elm-format adds two spaces between the comma and the function name in `exposing ()` if there is a comment below a function. 
```
module Test exposing
    ( test1
    ,  test2
       -- this comment causes the line above to be indented one space too far

    )
```
elm-format-0.19 0.8.0

**Comment by avh4** [comment]
Fixed in https://github.com/avh4/elm-format/pull/756
