### ISSUE TITLE
Comments not sticking to function definition

### ISSUE THREAD

**Issue by nullbio** [avh4/elm-format#553]
I noticed that  elm-format will put a new line between your comments and your function definition, i.e., saving the following:

```
{- comment 
-}
fn : String
```

Results in:

```
{- comment 
-}

fn : String
```

Just curious what the rationale behind this was, and if it's a standard to include it under the function signature instead, like so:

```
fn : String
{- comment 
-}
fn =
```

**Comment by avh4** [comment]
Documentation comments need to use `{-| .... -}` in order to be properly handled by Elm (in your example, the `|` is missing).  It should be grouped the the associated definition if you add that.

**Comment by nullbio** [comment]
Ah that did the trick, thank you. :-)
