### ISSUE TITLE
Elm 0.19 strings (and chars?) should allow literal tabs

### ISSUE THREAD

**Issue by hillerstorm** [avh4/elm-format#569]
Tabs as whitespace is forbidden in the Elm compiler, but it is however allowed inside strings.
The following code compiles and outputs the string with the tabs using `elm make` (0.19):

```elm
-- \t between a and b
temp1 : String
temp1 =
    "a	b"

-- \t between b and c
temp2 : String
temp2 =
    """a
    b	c"""
```

the resulting js:

```javascript
var author$project$Main$temp1 = 'a	b';
var author$project$Main$temp2 = 'a\n    b	c';
```

Running `elm-format` on the code above gives the following error message:
`SYNTAX PROBLEM: unexpected "\t" expecting string character or end of string`

**Comment by avh4** [comment]
Ah, thanks.  This appears to be an undocumented change between Elm 0.18 and Elm 0.19.

**Comment by avh4** [comment]
Thanks for the report!  This should be fixed by https://github.com/avh4/elm-format/pull/615
