### ISSUE TITLE
Problems when there is no space before a character literal (elm-version=0.19)

### ISSUE THREAD

**Issue by nonpop** [avh4/elm-format#575]
With elm-format 0.8.1, consider the following Main.elm file:
```elm
module Main exposing (main)

import Html


main =
    Html.text (String.fromChar '!')
```
With this file, elm-format has no problems. Now, if I remove the space before '!', elm-format will say:
```
-- SYNTAX PROBLEM ------------------------------------------------- src/Main.elm

I ran into something unexpected when parsing your code!

7│     Html.text (String.fromChar'!')
                                     ^
I am looking for one of the following things:

    a closing '''
```
If I remove the space AND change the character to 'c', it will instead remove the parentheses, turning the program into the incorrect
```elm
main =
    Html.text String.fromChar'c'
```
Also consider this version of the program:
```elm
module Main exposing (main)

import Html


main =
    let
        s =
            String.fromChar '!'
    in
    Html.text s
```
This time if I remove the space before '!', elm-format says:
```
-- SYNTAX PROBLEM ------------------------------------------------- src/Main.elm

(line 1, column 2):
unexpected "\n"
expecting literal character

10│     in
    ^
```
If I remove the space AND change the character to 'c', then it does not complain, but I would
expect it to add the space, which it does not do.

**Comment by avh4** [comment]
Ah, thanks!  This looks like it's because elm-format is still allowing `'` to be part of a variable name, which was removed from Elm's syntax in Elm 0.18.

**Comment by avh4** [comment]
This should be fixed in https://github.com/avh4/elm-format/pull/617
