### ISSUE TITLE
Cannot use empty record for pattern matching

### ISSUE THREAD

**Issue by nonpop** [avh4/elm-format#576]
Run elm-format 0.8.1 on the following file:
```elm
module Main exposing (main)

import Html


foo : {} -> String
foo {} =
    "42"


main =
    Html.text (foo {})
```
It fails with:
```
-- SYNTAX PROBLEM ------------------------------------------------- src/Main.elm

I ran into something unexpected when parsing your code!

7│ foo {} =
        ^
I am looking for one of the following things:

    a lower case name
    whitespace
```
The same thing happens if the empty record appears in a case branch. Matching against a variable works, and it also works if I change the empty records to empty tuples instead.

**Comment by avh4** [comment]
Ah, interesting -- this was not allowed in Elm 0.18, and I didn't see this syntax change in Elm 0.19 documented anywhere.

**Comment by avh4** [comment]
Thanks for the report!  This should be fixed in https://github.com/avh4/elm-format/pull/620
