### ISSUE TITLE
Expanding `exposing (..)` can hide elm-test tests

### ISSUE THREAD

**Issue by drathier** [avh4/elm-format#578]
In test files only exposed tests are run, and there's no way for the test runner to know if a test isn't exposed. I'd like to use elm-format when writing tests, but I'd also like everything to be exposed in test files so I don't accidentally skip some tests. It's more work to scroll up to the top of the file to replace the exposing list with `(..)` and run elm-format again to populate it with all tests, but mainly it's easy to forget about. I've gotten so used to elm just working that I usually write out the code and the tests, then run elm-test and when it passes, usually on the first try, I commit and move on.

I assume expanding `exposing (..)` is so that the public api isn't changed accidentally, or so that modules don't expose more than they have to, which is a worthwhile goal imo. I don't know if there are other reasons, or other tools to accomplish the same goal.

Possible solutions to the hidden tests problem:
1. copy/paste test files in elm-test and modify them to expose all tests, so we can at least know if there is an unexposed test in there
2. update all elm ide plugins to automatically expose new things written in test modules
3. stop expanding `exposing (..)` in elm-format
4. allow elm-format to distinguish test files from src files, and treat them differently
5. some other option?

**Comment by mattiasw2** [comment]
Having the same problem with expanding exposing and unit tests. I would really like a flag for it.

**Comment by kjda** [comment]
I'm sorry, but auto expanding `exposing (..)` is so stupid

**Comment by harrysarson** [comment]
How about an `elm-format --expand-exposing` (or similar) option?

**Comment by andys8** [comment]
I'd also prefer if this feature would be removed. It's far away from formatting code and there is no way to use the elm feature (`exposing (..)`) anymore.

It could be part of an editor plugin or a rule (including fix) in `elm-analyse` :)

**Comment by mordrax** [comment]
@kjda whilst I'm in agreement that the auto expansion of `exposing (..)` does not cater for our use cases, each of these decisions had been thought through and discussed to try to help elm developers. 

Your comment reads like a harsh non constructive criticism because it doesn't say why you think it's bad.

For me, it's a minor annoyance because I have to manually expose functions in a helper module for which I've intentionally declared to expose all helper functions.

**Comment by avh4** [comment]
Yeah, I agree that the auto-expanding is better done as a separate tool.  Though I'll note that having it has really helped the accidental broadening of modules in our large codebase at NoRedInk.

I'm planning for the auto-expanding to be removed by 1.0.0 if not sooner.

**Comment by andys8** [comment]
Sounds great. `elm-analyse` has a  `ExposeAll` check. It is enabled by default, but can be disabled.

https://stil4m.github.io/elm-analyse/#/messages/ExposeAll

There is currently no fixer implemented. But that seems to be the perfect place for this behavior to live on :)

https://github.com/stil4m/elm-analyse/tree/455a42cba07012a67f498bca106d35688a179c95/src/Analyser/Fixes

**Comment by mattiasw2** [comment]
I like that expose all can be expanded, I just do not want it all the time,
like for test files.

So, why not make it an argument?

Plz continue to do the good work you do, I use elm-format all the time.

/mattias

**Comment by avh4** [comment]
The expansion is removed in https://github.com/avh4/elm-format/pull/624

I agree that it might be useful to have this as an option, but I think it makes sense for now to remove this from elm-format and let people report about whether elm-analyse or other tools will meet their needs.  Specifically, https://github.com/avh4/elm-format/milestone/3 should provide some feature that will make it easy for automated refactoring tools or scripts to implement the expansion.

Also note that expansion will still be done for modules that don't have a module line.  (But modules with a module line that has `exposing (..)` will no longer be expanded.)

**Comment by avh4** [comment]
https://github.com/avh4/elm-format/pull/625 adds a new feature that allows a `module` line to not have an `exposing` clause -- in such cases, the `exposing` will be automatically generated.  This allows you to get the former expansion behavior by deleting the `exposing` clause before formatting.
