### ISSUE TITLE
UTF-8 long characters are encoded in a format elm make doesn't accept

### ISSUE THREAD

**Issue by Natim** [avh4/elm-format#584]
Here is the example:

```
let
  message = "\u{1F929} Show and Hide"
in
   Html.text "message"
```

With elm-format it becomes:

```
let
  message = "\x1F929 Show and Hide"
in
   Html.text message
```

With the following error:

```
Backslashes always start escaped characters, but I do not recognize this one:

117|             message = "\x1F92 9Show and Hide"
                            ^
Maybe there is some typo?

Hint: Valid escape characters include:

    \n
    \r
    \t
    \"
    \'
    \\
    \u{03BB}

The last one lets encode ANY character by its Unicode code point, so use that
for anything outside the ordinary six.


```

**Comment by avh4** [comment]
In your example, you show the output containing `\x1F929`.  That's en Elm 0.18 escape sequence, so I think you're inadvertently running elm-format in Elm 0.18 mode.  It will run in that mode if it sees a `elm-package.json` file in the current directory and not a `elm.json` file.

You can force it to run in Elm 0.19 mode with the `--elm-version=0.19` command line argument.  If you do that it should properly output as `\u{1F929}`.
