### ISSUE TITLE
fails to install on macos via nix

### ISSUE THREAD

**Issue by robx** [avh4/elm-format#585]
Compare https://github.com/NixOS/nixpkgs/issues/52118.

Apparently `elm-format.nix` is generated by `elm-format/package/nix/generate_derivation.sh`, so maybe the issue should be fixed here, by telling `cabal2nix` to not treat `elm-format` as a library?

**Comment by avh4** [comment]
Sounds like an accurate diagnosis, thanks!

> by telling cabal2nix to not treat elm-format as a library?

Does anyone know the necessary .nix change to do that?

**Comment by avh4** [comment]
I change the nix file to set `isLibrary = false`: https://github.com/NixOS/nixpkgs/pull/66364

**Comment by avh4** [comment]
Thanks for pointing this out!
