### ISSUE TITLE
elm-format converts '\xA0' to literal nonbreaking space character

### ISSUE THREAD

**Issue by pschultz** [avh4/elm-format#598]
Before elm-format:

```elm
noBreakSpace =
    '\xA0'
```

After elm-format:

```elm
noBreakSpace =
    ' '
```

The literal character is correct, so the formatted definition is still equivalent.

In #457 you say "elm-format escapes all whitespace characters except the normal space, with the intent of making it obvious when special spaces are being used" but this is the exact opposite behavior. 

In general I would prefer if elm-format left any escape sequences as authored. I can understand that converting things like non-0x20 spaces to escape sequences may be helpful. But I can't think of a single scenario where changing one escape sequence to another (#376) or changing an escape sequence to the literal UTF-8 character like here would not be surprising. I don't think escape sequences end up in source code by accident; they are always put there intentionally.

**Comment by avh4** [comment]
Older versions of elm compiler had a bug on Windows where having an escaped `\xA0` in an elm file caused the compiler to crash, so elm-format made that character into a literal non-breaking space to work around that bug in elm compiler.

Supposedly Elm 0.19 compiler no longer has that bug, so elm-format should change to always use escaped non-breaking space (which will be `\u{00A0}` in Elm 0.19 escape syntax).

That workaround was removed here: https://github.com/avh4/elm-format/pull/496

**Comment by avh4** [comment]
It needs to be confirmed that Elm 0.19 no longer crashes on Windows when the source file contains `"\u{00A0}"`

**Comment by avh4** [comment]
Turns out this was already fixed for `elm-format --elm-version=0.19` in https://github.com/avh4/elm-format/pull/496.

This cannot be fixed for `elm-format --elm-version=0.18` because Elm 0.18 crashes on Windows (https://github.com/elm/compiler/issues/1279) if the source file contains `\xA0` in a String or Char literal.

Thanks for the report!
