### ISSUE TITLE
Test release binaries on Windows to ensure that we're not affected by "Access violation in generated code"

### ISSUE THREAD

**Issue by avh4** [avh4/elm-format#609]
Reports in https://github.com/elm/compiler/issues/1797 suggest that it's possible that recent versions of ghc produce bad Windows binaries

**Comment by Kurren123** [comment]
Actually I would say that recent versions of GHC have fixed the access violation issues. I'll look for the GHC ticket which claimed it was resolved.

**Comment by avh4** [comment]
I tried running the latest appveyor artifact on Windows 10 (x64) and there were no crashes.

**Comment by avh4** [comment]
I tried running elm-format on a large directory of elm files in a Windows 10 admin console.  This included some unformatted files (so files were written to disk), and included interactive confirmation.

So I think everything should be good.
