### ISSUE TITLE
Format stdin

### ISSUE THREAD

**Issue by avh4** [avh4/elm-format#66]
*As a build tool author,
I want `elm-format` to be able to read from stdin and write to stdout
So that my build tool can format Elm code without first having to write it to a file*

--

Running `elm-format --stdin` should read stdin instead of a file, and write the result to stdout.

Review the usage docs to make sure they are consistent with this and mention that this can be done.

**Comment by avh4** [comment]
To support #65

**Comment by eeue56** [comment]
How do you see end-of-input working? Usually on UNIX it's `Ctrl-d`. Would you expect the same here?

**Comment by avh4** [comment]
I would expect whatever haskell mechanism is used for reading stdin should provide a way of determining end-of-input.  See http://ubuntuforums.org/showthread.php?t=1795636 for one example.  (I don't know haskell that well to know if the example there is the best way to read stdin or not.)

See also http://unix.stackexchange.com/a/110248 for background on how EOF normally works.

**Comment by eeue56** [comment]
Yup - just confirming that you wanted it to work with actual EOF rather than some other way of inputting text. I should get time this weekend to take a stab at this and moving some of the `Main` tests over.

**Comment by avh4** [comment]
Cool!

I don't know what other options there would be, but I'd be curious to hear about any good ones.

**Comment by eeue56** [comment]
This would the best way to do it I think - just wanted to check the spec before I made it. 

I don't think there's really any other nice way of doing it, other than maybe opening an editor session from their settings (like git does for commits). Then they could paste it, it would be saved to a temp file and formatted, then giving them the option to save it back to a real file or copy it to clipboard. But I don't really think that's necessary here!

**Comment by avh4** [comment]
Ah, yes, the reason for adding this is to support IDE plugins and other build tools that will want to run elm-format without needing to have the source code saved in a file.  (See #65)  So this definitely needs to be non-interactive.

**Comment by avh4** [comment]
Fixed in #82
