### ISSUE TITLE
Error message reported far from actual problem when extra comma inserted

### ISSUE THREAD

**Issue by ianmackenzie** [avh4/elm-format#666]
The following code has an extra comma in the second list:

```elm
module Main exposing (main)


main : Type
main =
    foo
        { x =
            [ a
            , b
            , c
            ]
        , y =
            [ d
            , e,
            , f
            ]
        }
```

However, the reported error points to the very start of the record and doesn't seem to relate to the actual problem at all:

```
ERRORS
-- SYNTAX PROBLEM ----------------------------------------------------- Main.elm

I ran into something unexpected when parsing your code!

7|         { x =
             ^
I am looking for one of the following things:

    a closing bracket '}'
    whitespace
```

I'm using `elm-format` 0.8.2 on Windows 10.

**Comment by MartinSStewart** [comment]
@ianmackenzie Shouldn't this issue go in https://github.com/elm/compiler/issues instead or elm-format?

**Comment by ianmackenzie** [comment]
No, this is an `elm-format` error - `elm make` gives this on the same file:

```
-- UNFINISHED LIST ---------------------------------------------------- Main.elm

I was expecting to see another list entry after that last comma:

13|             [ d
14|             , e,
15|             , f
                ^
Trailing commas are not allowed in lists, so the fix may be to delete the comma?

Note: I recommend using the following format for lists that span multiple lines:

    [ "Alice"
    , "Bob"
    , "Chuck"
    ]

Notice that each line starts with some indentation. Usually two or four spaces.
This is the stylistic convention in the Elm ecosystem.
```

**Comment by MartinSStewart** [comment]
Oh, my mistake. I didn't realize elm-format provides error messages!

**Comment by ianmackenzie** [comment]
It seems to! Unless there's something weird going on where `elm-format` is implicitly invoking `elm make`, and it's finding some old version of Elm on my machine that's different from the one on my PATH...which I wouldn't be entirely surprised by, but as far as I can tell that's not what's happening.

**Comment by rlefevre** [comment]
This comment is related:

https://github.com/avh4/elm-format/issues/662#issuecomment-583802690

It might be preferable to rely on `elm make` for syntax errors.

**Comment by ianmackenzie** [comment]
Makes sense! I guess it would be easy enough to make an `elm-try-format` or similar script/alias that would run `elm make --output=/dev/null` and then `elm-format`...

**Comment by avh4** [comment]
As of elm-format 0.8.5, elm-format no longer reports detailed error messages; the intended use is now to run `elm make` to get the detailed error if elm-format fails.  So I think this issue is no longer relevant.  Thanks for the original report.
