### ISSUE TITLE
comment wierdness when no imports

### ISSUE THREAD

**Issue by simonh1000** [avh4/elm-format#679]
See how the comment is no linked to the first declaration. If I add an import statement, it is linked

![image](https://user-images.githubusercontent.com/5256724/84355798-82397f00-abc3-11ea-99e7-e62ac2141462.png)

**Comment by avh4** [comment]
This is actually how elm itself will parse the file: the first comment in this case will be considered the module comment.  So elm-format is simply formatting to make it clear how elm will parse the file.

To make the comment be associated with the declaration, you have to either add a module comment above the declaration comment, or add an import.
