### ISSUE TITLE
Single-constructor union types error

### ISSUE THREAD

**Issue by rtfeldman** [avh4/elm-format#68]
To reproduce, run `elm-format` on this:

```
module Foo (..) where


type Bar
    = Baz
```

*Expected:* No change
*Actual:* Kaboom!

**Comment by avh4** [comment]
Can't repro.  This may have been fixed in df38e444bcb59eb8eb98a8ffc29bbeccc44698c1.  Did you pull that yet?

**Comment by avh4** [comment]
Reopen if this is still an issue on master.

**Comment by rtfeldman** [comment]
Just pulled and confirmed it's fixed! :+1:
