### ISSUE TITLE
Backticks-within-backticks in documentation is destroyed by elm-format

### ISSUE THREAD

**Issue by malaire** [avh4/elm-format#682]
Following format is correct way to include backticks-within-backticks: ``` `` `0` `` ```.

However `elm-format` doesn't like this but changes ``` `` `0` `` ``` to ``` ``0`` ``` which removes the backticks around `0` and completely destroys intended text.

**Comment by avh4** [comment]
Fixed in https://github.com/avh4/elm-format/pull/691, will be included on v0.8.4

**Comment by avh4** [comment]
And thanks for the report of this!

**Comment by avh4** [comment]
0.8.4 is now released with this fix: https://github.com/avh4/elm-format/releases/tag/0.8.4
