### ISSUE TITLE
Negative hex numbers get corrupted

### ISSUE THREAD

**Issue by Janiczek** [avh4/elm-format#688]
[Screencast](https://streamable.com/6wdcto)

**`-0xFFFFFFFF` (valid Elm) becomes `0xFFFFFFFF00000001` (invalid Elm).**

`-(0xFFFFFFFF)` doesn't help.
`(-0xFFFFFFFF)` doesn't help.
The only workaround is `(negate 0xFFFFFFFF)`.

**Comment by avh4** [comment]
Thanks for this!  I expect to get a look at this in the next week or two.  Do you happen to know what the max hex int allowed by elm-compiler is?

**Comment by Janiczek** [comment]
Looks like it breaks down around 
`0x7FFFFFFFFFFFFFFF` :heavy_check_mark: 
`0x8000000000000000` :x:

![experiment](https://user-images.githubusercontent.com/149425/91094831-a867aa80-e65b-11ea-800b-b3fd1988daf7.png)

**Comment by avh4** [comment]
Ah, okay, looks like any negative hex int will be converted into a positive hex int, with 16 digits, which Elm 0.19 doesn't allow.

**Comment by avh4** [comment]
Fixed in https://github.com/avh4/elm-format/pull/697, and will be in elm-format 0.8.4

**Comment by avh4** [comment]
0.8.4 is now released with this fix: https://github.com/avh4/elm-format/releases/tag/0.8.4
