### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by rtfeldman** [avh4/elm-format#70]
If you'd like a roughly pathological case to test, here's a 900-LoC real-world Elm file: :stuck_out_tongue_winking_eye: 

https://github.com/rtfeldman/elm-css/blob/d9bae597431980a12fc58c568b74b9decfc1eff1/src/Css.elm

**Comment by avh4** [comment]
Good news, I don't understand why, but #58 improves the runtime for `Css.elm` from 1m27s to 0.14s!

**Comment by rtfeldman** [comment]
![motherofgod](https://cloud.githubusercontent.com/assets/1094080/11662473/a773866c-9d8b-11e5-86d3-17919c4dbebc.jpg)

**Comment by rtfeldman** [comment]
I just hit Save in Sublime Text and it formatted the whole thing instantly. :scream:

**Comment by rtfeldman** [comment]
`Css.elm` is now over 4,000 LoC and I'm happy with the performance, so I'm gonna close this. :rocket:
