### ISSUE TITLE
More than one way to format the file

### ISSUE THREAD

**Issue by Janiczek** [avh4/elm-format#71]
Might be relevant to #59 (unnecessary parens)

If I pass elm-format the unformatted code:
```elm
foo bar =
  case bar of
    (x::xs) ->
      Just x
    [] ->
      Nothing
```
it formats it to this:
```elm
foo bar =
    case bar of
        (::) x xs ->
            Just x

        ([]) ->
            Nothing
```
where the patterns aren't very satisfying.
*(Should I put the `(::)` case in its own issue?)*

Also when I try to delete the round parens, it allows me to do that *(there should probably be only one way to do it?)*, but when I change the `(::)` case, it reverts everything back. See:
![a](https://cloud.githubusercontent.com/assets/149425/11506627/a6f288e0-9850-11e5-9d96-f5eac2c9978c.gif)

**Comment by avh4** [comment]
Also found this case:

```
-                Err _ as err ->
+                (Err _) as err ->
```

**Comment by avh4** [comment]
I think this is fixed now.  Can you confirm?

**Comment by Janiczek** [comment]
For me it produces:
```elm
foo bar =
	case bar of
		(::) x xs ->
			Just x

		([]) ->
			Nothing
```
which then produces an error:
```
ERRORS
-- SYNTAX PROBLEM --------------------------------------------------- <location>

I ran into something unexpected when parsing your code!


I am looking for one of the following things:

    whitespace
```

which means that it's not idempotent (which it should be!):
```
f(f(x)) = f(x)
```

**Comment by avh4** [comment]
Is it the 0.1-alpha3 version of elm-format?  If not, which commit did you build from (`git show --oneline`)?  Also, can you give the output of `locale`?

**Comment by Janiczek** [comment]
Built from source, it was:
c618ade `Reorder the editor integration sections`

```bash
$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=cs_CZ.UTF-8
LC_TIME=cs_CZ.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=cs_CZ.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=cs_CZ.UTF-8
LC_NAME=cs_CZ.UTF-8
LC_ADDRESS=cs_CZ.UTF-8
LC_TELEPHONE=cs_CZ.UTF-8
LC_MEASUREMENT=cs_CZ.UTF-8
LC_IDENTIFICATION=cs_CZ.UTF-8
LC_ALL=
```

**Comment by avh4** [comment]
Hmm, I still can't repro.  c618ade includes a5bf3ba005f2972ee163ef88c11561213d7d2204, which makes infix operators format properly in patterns.

You may have three different elm-formats:
 - `./dist/build/elm-format/elm-format`  (updated when running `cabal build` or `./tests/run-tests.sh`)
 - `./.cabal-sandbox/bin/elm-format`  (updated when running `cabal install`)
 - `/usr/local/bin/elm-format`  (not updated by cabal)

Can you double-check that you're running the version you think you are?

**Comment by Janiczek** [comment]
```bash
$ which elm-format
/var/www/html/elm-format/.cabal-sandbox/bin/elm-format
$ git pull upstream master
$ cabal install -j
$ tests/run-tests.sh
```

When I did this again, it all started working (to the point that we can close this issue). Go figure :)
