### ISSUE TITLE
release convention of use prelease tag

### ISSUE THREAD

**Issue by chenrui333** [avh4/elm-format#712]
👋 I am a homebrew-core maintainer, I am trying to keep elm-format up to date with [this PR](https://github.com/Homebrew/homebrew-core/pull/61596), but I run into some tagging issue (`prelease` vs `latest`).

I wonder if I can get some sense about the tags usage as well as any plan moving to the `latest` release, as that is more github native.

Thanks!

**Comment by avh4** [comment]
Pre-release for elm-format has just meant that it's pre-1.0.0.  But I guess there isn't really a reason to keep labelling it that way.  I've just removed the "pre-release" indicator from https://github.com/avh4/elm-format/releases/tag/0.8.4

**Comment by chenrui333** [comment]
thanks for being flexible, appreciate it!

**Comment by avh4** [comment]
I think this is resolved
