### ISSUE TITLE
Pattern Matching for Negative Numbers

### ISSUE THREAD

**Issue by Orasund** [avh4/elm-format#718]
pattern matching over negative numbers will be transformed into invalid code:

```
case int of
  -1 ->
    0
  n ->
    n
```

will be turned into

```
case int of
  (-1) ->
    0
  n ->
    n
```

which results in the following error:

```
UNFINISHED PARENTHESES - I just saw an open parenthesis, but I got stuck here:

27|                         (-1) ->
                             #^#
I was expecting to see a pattern next. Maybe it will end up being something like
#(x,y)# or #(name, _)#?
```

**Comment by avh4** [comment]
Apparently the fixed version is no longer valid either in Elm 0.19.  https://github.com/elm/compiler/issues/1773

So I guess this fix doesn't need to be applied for Elm 0.19
