### ISSUE TITLE
should [a] become a :: [] in pattern matches?

### ISSUE THREAD

**Issue by avh4** [avh4/elm-format#77]
In a pattern match, `[a]` currently becomes `a :: []`.  This was not intended, but is it desirable?

**Comment by Apanatshka** [comment]
hmm, `a :: []` looks like a "normal form". That can be a good thing, but in this case the `[a]` is more familiar and it's there on purpose. Unless you *want* to discourage special list syntax, I'd standardise on using it when possible.

**Comment by avh4** [comment]
In addition, a pattern like `[a,b,c]` will currently become `a :: b :: c :: []`.  Interestingly, `elm-compiler` converts to that same form when reporting errors:
```
You need to account for the following values:

    []
    _ :: []
    _ :: _ :: []
    _ :: _ :: _ :: _ :: _

Add branches to cover each of these patterns!
```

**Comment by avh4** [comment]
Also note that the `::` is already a special case in patterns, since there are no other infix constructors.  (At least, I think that's the case.)

**Comment by eeue56** [comment]
+1 for keeping it `[a]`

While I like the idea that `a :: []` promotes (matching against an empty tail), I still think `[a]` reads better as "the only thing in the list"

**Comment by avh4** [comment]
As of 141c761, list patterns will not be transformed into the binary constructor equivalent.
