### ISSUE TITLE
Infix operators longer than 4 characters should wrap following expression

### ISSUE THREAD

**Issue by avh4** [avh4/elm-format#78]
```elm
foo =
    a
        `plus` (b
                   + c)
```

Should become
```elm
foo =
    a
        `plus`
            (b
                + c)
```

**Comment by Apanatshka** [comment]
I hope you don't mind me saying that this looks pretty bad either way...
I'd expect that if the operator and right-hand side are indented enough that they fit next to the left-hand side, you'd put it there and not on the next line:

```elm
foo =
    a
        `plus`
            (b + c)
```

**Comment by avh4** [comment]
This is meant for when the input file had a linebreak before the `+`, or when `b` is a multiline expression,  so the example I gave is not the best representation of when this might occur in real code.

The intent of this is to change how far `(b` (and everything inside those parens) is indented.

**Comment by Apanatshka** [comment]
oh ok, never mind then :)

**Comment by avh4** [comment]
No one really seems to care about this.  I'm going to close this until someone actually things it's important in a real code example.
