### ISSUE TITLE
Documentation comment before first declaration gets spaces added if no import present

### ISSUE THREAD

**Issue by rtfeldman** [avh4/elm-format#79]
To reproduce:

```elm
module Quiz.Layout (..) where

{-| This is a documentation
  comment that I tried to put
  right above the first declaration here:
-}


foo = 
    "bar"
```
If you try to put the documentation comment right above `foo`, the spaces in between them reappear.

If you add an `import` below `module`, the documentation comment moves to the expected place.

**Comment by avh4** [comment]
@rtfeldman in the example file you've given,  `elm-make` will interpret that comment as the module documentation, not as the documentation for `foo`, so elm-format is actually correct in this case.

**Comment by rtfeldman** [comment]
Ah, interesting. Seems like a bug in `elm-make`, but I can't imagine a time when it'd be worth changing.

**Comment by avh4** [comment]
You can work around it by doing

```elm
module Quiz.Layout (..) where

{-| -}


{-| This is a documentation
  comment that I tried to put
  right above the first declaration here:
-}
foo = 
    "bar"
```
