### ISSUE TITLE
Change to 2-space indentation

### ISSUE THREAD

**Issue by avh4** [avh4/elm-format#80]
Discussion on elm-dev reveals that many people prefer 2-space indentation.  Consider whether we need to collect more information/options, what criteria we want to use to decide which to settle on, and if we want to switch to 2-space, review a few examples of what it will look like.

**Comment by avh4** [comment]
Discussion on elm-dev: https://groups.google.com/forum/#!topic/elm-dev/1fWxZPcQVqI

**Comment by avh4** [comment]
General opinion from elm-dev is that more than 80% of people prefer 2-space indent.  We will use 2-space indentation in beta3 and see if there are any sever problems.

**Comment by avh4** [comment]
Fixed in 14157d6

**Comment by lovesowing** [comment]
this doesn't seem to be the current behavior as of 0.8.8, when did this get changed?

**Comment by lydell** [comment]
@jkellogg01 https://github.com/avh4/elm-format/issues/158#issuecomment-219262937
