### ISSUE TITLE
Non-idempotent Block Comment reformatting

### ISSUE THREAD

**Issue by rtfeldman** [avh4/elm-format#90]
To reproduce:

1. Run elm-format on [this file](https://github.com/rtfeldman/elm-css/blob/d83794c6b215a58d3d6f7518328fc6cd0b810695/src/Css.elm)
2. Run it again.

Notice that some of the block comments ([this one](https://github.com/rtfeldman/elm-css/blob/d83794c6b215a58d3d6f7518328fc6cd0b810695/src/Css.elm#L872-L887) and [this one](https://github.com/rtfeldman/elm-css/blob/d83794c6b215a58d3d6f7518328fc6cd0b810695/src/Css.elm#L891-L900)) have been scooted over even further!

Each time elm-format gets run on this file, they get scooted over further and further.

**Comment by avh4** [comment]
I *thought* there was a bug like this lurking around somewhere :)

**Comment by rtfeldman** [comment]
Nothing quite like a large corpus of real code to find edge cases. :D

**Comment by avh4** [comment]
Fixed in 1846180.  The behavior is a bit clever: excluding the first line, it will strip leading whitespace from the comment block and then indent that block to be aligned with the first line of the comment.  Let me know if you find any cases where this does the wrong thing.
