### ISSUE TITLE
Import alignment

### ISSUE THREAD

**Issue by patrickdet** [avh4/elm-format#91]
Hey all,

maybe this has been discussed before and maybe it's just me but I like to align my imports like this:

```Elm
import App.Model  as App exposing (Model)
import App.Update        exposing (Action)
import Event             exposing (Model, initialModel, update)
import RouteHash         exposing (HashUpdate)
```

and not like:

```Elm
import App.Model as App exposing (Model)
import App.Update exposing (Action)
import Event exposing (Model, initialModel, update)
import RouteHash exposing (HashUpdate)
```

I feel that the former makes it easier to perceive at a glance what is going on.

**Comment by Janiczek** [comment]
http://wconrad.github.io/20150627/tabular-alignment-antipattern.html

**Comment by patrickdet** [comment]
@Janiczek :+1: you are right. thank you :)
