### ISSUE TITLE
Licensing of contributions: @Janiczek

### ISSUE THREAD

**Issue by avh4** [avh4/elm-format#94]
@Janiczek can you please verify whether the copyright for [your previously-merged contributions to elm-format](https://github.com/avh4/elm-format/commits?author=Janiczek) is owned by you and state that you are licensing your contributions under the [BSD-3-Clause](http://opensource.org/licenses/BSD-3-Clause) license.

Please also make a new PR adding yourself to the `LICENSE` file (add a new line for yourself in the very top section).

Thanks!

**Comment by Janiczek** [comment]
Yeah I confirm that :)

**Comment by avh4** [comment]
Great, thanks!  :)
