### ISSUE TITLE
Licensing of contributions: @eeue56

### ISSUE THREAD

**Issue by avh4** [avh4/elm-format#95]
@eeue56 can you please verify whether the copyright for [your previously-merged contributions to elm-format](https://github.com/avh4/elm-format/commits?author=eeue56) is owned by you and state that you are licensing your contributions under the [BSD-3-Clause](http://opensource.org/licenses/BSD-3-Clause) license.

Please also make a new PR adding yourself to the `LICENSE` file (add a new line for yourself in the very top section).

Thanks!

**Comment by eeue56** [comment]
confirmed :+1: and the PR is here - https://github.com/avh4/elm-format/pull/96

**Comment by avh4** [comment]
Great, thanks!  ✅
